### ISSUE TITLE
Switch QuickSort to Vanilla Sorting Scripts

### ISSUE THREAD

**Issue by Misunderstood-Wookiee** [Misunderstood-Wookiee/Mules-and-Warehosues-Extended#1]
Mules use a custom quicksort.xml. this is no longer required due to current updates to the game adding functional vanilla sorting scripts. 

Re-work the sorting in mule logics to be based on vanilla calls.

**Comment by bhayden53** [comment]
With the re-write of supply mule, this quicksort script will no longer be needed anyway.
