### ISSUE TITLE
Supply Mule: Slider "Max Trade" doesnt work

### ISSUE THREAD

**Issue by morgenrot68** [Misunderstood-Wookiee/Mules-and-Warehosues-Extended#100]
Hello,
Unfortunately I found a new possible bug.

It concerns Supply Mule.
The slider Max Trade seems to have no function.
Only one trade is generated at a time.

I have now tested this very extensively.
I can't get the ship to generate more than one trade.
No matter how I adjust the slider. 
If I set it to 10, trades should be generated at least 10% of the freighter level. (set to 5, 20% etc.) 
Example:
I want to buy smart-chips (1x chip fills 2 qm).  The ship has a freighter capacity of 45.000 qm.
I have set 'Trade Max' to 10. 
After that, offers to buy over 10% of the freight capacity, (2250 chips) would have to be generated. 
A buy offer of 60.000 chips is generated by the target station. The price is also right.
There are several factories within jumping range, offering over 2250 smart-chips. Several trades would have to be generated. But only one trade is generated at a time. Not a big trade, but a small one, which is a little over the 10% freighter capacity. More trades would have been possible. But these were not generated. I have tested different 'Trade Max' settings. Only one trade is generated at a time. As I said, I also made sure that all other parameters are ok. (price, buy offer etc.)

Therefore I think it is a bug.

**Comment by Galaxy-Spam** [comment]
Dublicate of #90 .
Fix is on the way, but not trivial and will take some time. Maybe a beta next week.

**Comment by morgenrot68** [comment]
Hello,

Have you made any progress with this?

**Comment by Misunderstood-Wookiee** [comment]
Pretty sure this is fixed in the later versions this bug report was made 2 years ago.
