### ISSUE TITLE
Supply Mule: Please implement selectable source stations/warehouses.

### ISSUE THREAD

**Issue by morgenrot68** [Misunderstood-Wookiee/Mules-and-Warehosues-Extended#101]
Supply Mule: Please implement selectable source station/warehouse.

The following situation:
I would like to supply my own factory from two own warehouses. The two own warehouses serve as warehouses to supply an own factory. I would like to choose from which warehouses or factories the supply should take place. But unfortunately this is not possible. Or I do not know how.

I would like to have a possibility to choose, like with the Travel Mule, but vice versa. That means, instead of selecting the target stations, you should be able to select the stations that supply the target station (or warehouse). Preferably independently, whether own stations or NPC stations. 
This would be very desirable. This possibility is completely missing.

**Comment by Misunderstood-Wookiee** [comment]
Does Home Station/Sector not work?

**Comment by morgenrot68** [comment]
Hello,
I don't think I've explained what I mean very well.
I'll give an example:

I have several ore refineries. I want to bring the refined metals from these stations to my drive parts factory (with one ship).

Unfortunately, this is not possible. I have to be able to select several source stations and one destination station. 

I am often faced with this problem. I would like to buy goods or resources from different selectable stations or warehouses and deliver them to a destination station.

This possibility is missing, but it happens very often in my way of playing.

**Comment by DeeparthGupta** [comment]
You can create a trade rule where your faction is the only one getting traded with and apply that rule to the refined metal input of your parts factory. A single ship may take a little while to start supplying your parts factory.
