### ISSUE TITLE
investigate using the trader role for subordinates instead of defence

### ISSUE THREAD

**Issue by bhayden53** [Misunderstood-Wookiee/Mules-and-Warehosues-Extended#11]
It would be super convenient for users if mules that are subordinates used the trader role instead of the defence role.

**Comment by Vectorial1024** [comment]
Perhaps my mod Civilian Fleets would be of some help:

https://github.com/Vectorial1024/v1024_civilian_fleets

Once the Mules' parameters are finalized, I can add support to the Mules on my side.

**Comment by bhayden53** [comment]
@Vectorial1024 what needs to be finalized on our side? The list of params?

**Comment by Vectorial1024** [comment]
Yes, the list of parameters of each of the Mules need to be finalized.

Then, by referring to the list of parameters, I can tell my mod to correctly copy Mules' commands between ships.

Still, my mod only handles cases where ships are to be assigned under the Mules. To handle cases where Mules are to be assigned to stations, some extra script is needed.

**Comment by Misunderstood-Wookiee** [comment]
Added as of https://github.com/Misunderstood-Wookiee/Mules-and-Warehosues-Extended/commit/8d7abd7994868a2babf3dce3735b446d4c0271be
