### ISSUE TITLE
[Potential Bug]: I think I found a bug!

### ISSUE THREAD

**Issue by Midnitewolf** [Misunderstood-Wookiee/Mules-and-Warehosues-Extended#110]
When using Supply Mule, when a trader buys from an NPC station and brings the ware back to my station, the sale is listed as a profit in both the station transaction log and the general logbook.  Basically my station thinks it is making a profit off itself. 

Not sure if this is a limitation of the game engine or the mod but the obviously make it hard to keep track of profitability and costs.  I am also not sure what else this might effect such as perhaps a stations expected operating budget because this station is also auto-transferring small sums from the station account to my individual account as if it was actually making a profit off itself. 

Note: Maybe I am just not understanding how it works to "balance" the books so to speak.

**Comment by bhayden53** [comment]
What this number is telling you, is the difference between how much you would have paid _had you bought from the AI at your station_, versus how much you actually paid by _going out and buying the ware yourself at a lower price_.

We don't touch the transaction log. That is a new thing. If you assign the supply mule to the actual station, he will use that stations budget, and the transaction should show up in that log with the proper numbers.

The logbook, we write the difference between the price that you bought the ware, and the amount that your station would have paid for it. So think of that number as the discount you got by hunting for a deal yourself.

I only use the transaction log at a station or for a ship to evaluate profit these days. 

TBH we should probably just remove the logbook entry, it's been replaced by Egosoft's transaction log, which works much better.

**Comment by Midnitewolf** [comment]
OK I sort of get it (not really hehe).  To be honest it seems that this sum shouldn't exist at all.  I mean if your buying from an NPC and not reselling, the transactions should just all be negatives.  It is really confusing seeing positive transactions show up that apparently aren't actually happening.   Thanks anyway.

**Comment by bhayden53** [comment]
In the past it was actually a bit unclear exactly when money was changing hands. It is more clear now with the transaction log so as I said, I'm potentially inclined to remove our logbook entries altogether.
