### ISSUE TITLE
[QUESTION]: Supply Mule Challenges

### ISSUE THREAD

**Issue by Chh2tx** [Misunderstood-Wookiee/Mules-and-Warehosues-Extended#111]
> Check available  [Informational Material and F.A.Q](https://github.com/Misunderstood-Wookiee/Mules-and-Warehouses-Extended/blob/Public/README.md)  before posting.

**I would like the know the following:**
Not sure if a bug, or I'm doing something wrong. I've read the Wiki and searched everything I can find. I'm having trouble with the supply mules honoring the 'Lock Wares' function.

I'll go through and configure the mule to only trade in 3 wares and I 'lock' them in (Energy Cells, MREs and Med Supplies from TER econ). The moment I click confirm and it finds the first trade, all other raw resource and intermediates are added, including minerals/gas, substrate and it'll trade in all those wares as it finds orders. (This is with Build storage, resources, intermediates, tradewares checked).

If I go through and do the exact same thing, select only the 3 wares, lock them in, but do not check build storage, resources, intermediates or tradewares, then mule just sits and never finds a trade.

If I do the same thing, select only the three wares, lock them in, and check resources as well -- It'll add all resources to the ware list beyond the ones I locked in and started trading in all those listed wares.

From what I read, I should be fine to select any of the 4 options (Build, Resources, Intermediates, Tradewares) which enables them to fill a need in that category, but they should honor 'lock wares' that they'll only trade in specific wares I select that are in need.

Am I not understanding and doing something wrong if I wanted to setup some traders the deal specifically in certain wares and not others. I'm trying to do the same with high tech goods fleet. I don't necessarily want a single supply feet as they all follow the same priority so they'll all pivot to what it deems as high priority and neglect some lower priority needs. ie If I get aggressive building stations, they'll all swap to build storage hauling and neglect the core resources needed to keep existing operating stations supplied with ECs, MREs and med supplies.

I'm not using tradestations just yet, and I was utilizing the supply fleets to service all stations instead of assigning to station.

**Comment by bhayden53** [comment]
thanks for the report; I will take a look as soon as I can (probably sometime in the next few hours)

**Comment by bhayden53** [comment]
Are you clicking the "lock wares to User selection" button?

**Comment by bhayden53** [comment]
I'm simply double-checking what you mean by "lock them in", because so far I am debugging and everything is working as intended for me...

**Comment by Chh2tx** [comment]
Yes, by lock them in I mean I'm selecting to 'Lock wares to user selection'.
 
 For example I was attempting to create a High Tech Goods Fleet.
I selected to Lock Wares, and chose Silicon Carbide, Metallic Microlattice and Computronic Subtrate.
Buildstorage, resource, intermediates, and tradewares unchecked. Mule does nothing, sits and searches.
Turn on 'resources', and the trader would create an order for Energy Cells, as well as adding all minerals and MREs etc. as soon as I clicked confirm.

Screenshots
These are the options I  start with: https://imgur.com/a/njmHEFc
Click confirm, options stay the same, but the mule just sits 'searching for trades': https://imgur.com/a/tt8NHUC
Click and turn Resources ON, and nothing else, mule adds raw wares and then immediately finds a trade: https://imgur.com/a/hjapOTF  
Image of the order in the log https://imgur.com/a/nHVDs3s

From what I read, I SHOULD be selecting some of the 4 options defined below, in order for the mule to trade at all, which seems to be what happens as it doesn't move at all without one of them selected. I take these to mean they are not intended to be preset ware lists but telling the mule at what point in the supply chain it CAN trade, and the ware list I'm attempting to 'lock wares' to should be the only wares it's allowed to trade.
_"Allow Buildstorage / Resources / Intermediates / Tradewares - allow mule to supply the stations build storage / resources / intermediates / tradewares"_

It just doesn't appear it keeps itself restricted to the wares I selected and adds all resources the station has orders for. And if I don't select any of those 4 options, It stays on searching indefinitely, despite orders existing.

Am I misunderstanding or misusing if I'm just trying to use Supply Mules, without warehouse or tradestation, to supply stations. I currently have two fleets I'm trying to manage this with. Agricultural (Energy Cells, MREs, Med Supplies) and High Tech (Silicon Carbide, Computronic Substrate, Metallic Microlattice) but I keep finding them expanding into wares I've not chosen or they do nothing at all.

**Comment by Chh2tx** [comment]
I took a video of what I'm referring to. Maybe this helps?

https://drive.google.com/file/d/1GSZSuhEGsQN4M3tRL2ea_6v1cGu2WKFZ/view?usp=sharing

This autopopulation with all wares of the station to supply seems like exactly what it's doing, despite selecting to lock wares to the ones I've chosen.
_"Warebasket - Wares the mule trades with (if not locked, will be autopopulated and updated by the script with all wares of the station to supply)"_

**Comment by bhayden53** [comment]
I am not seeing that behavior, can you confirm where you installed mules from? Are you just using the steam subscription?

I can't test it right now, but you shouldn't need to untick everything like resources/intermediates/tradewares first. Leave those all checked and just pick the wares and lock them.

**Comment by Chh2tx** [comment]
Installed from Nexus

**Comment by bhayden53** [comment]
which exact link, someone deployed their own version of mules to nexus, just want to be extra explicit here that you're actually using our code

**Comment by Chh2tx** [comment]
https://www.nexusmods.com/x4foundations/mods/416 Is the one I used. I believe it's the correct one. Last modified 3/25

![image](https://user-images.githubusercontent.com/47042057/113305500-b607a180-92c8-11eb-9269-6379171a8e54.png)

**Comment by Chh2tx** [comment]
It does the same thing if I never touched the BuildStorage, Resources, intermediates, or  Tradewares and leave those default checked. I just did it in my game. I can take another video if needed.

I literally only uncheck 'Allow Ai Suppliers', and check 'Lock Wares' and chose the same 3 wares as the video. Immediately after clicking confirm, it queues up a trade for Energy Cells and sets off for the Solar Power Plant.

Worth noting that when it does the above ^, it doesn't show all the wares like the first video does, but it still queues for unselected wares for trade.
Here's a video of the above, never touching the resources or similar items, https://drive.google.com/file/d/1mJ3FSIDu5ArjDp3TMIcHUWwFc5nk5rlu/view?usp=sharing

Edit: I'm not using any economy or war mods. Only other trade related mod installed is TaterTrader, which I only use for AI station trading. The only other 'orders/behaviors' mods are Janpanthera's suite SatDropper, CollectDrops/Placeabless, Another Explorerv3. And the video above is a fresh restart of the client and load of the save as I shut down after the first video last night, and taking the new video this morning.

**Comment by bhayden53** [comment]
So I do exactly what you did in your video(s) and I simply cannot reproduce this at all. My locked warelist is always respected in every test I am running. I have tried every combination of settings I can think of and everything is rock solid.

Do you have any mods installed that might be messing with the UI? My suspicion is that something you have installed is breaking our "lock wares" button.

I could use some debug logs if you're willing. 

https://gist.github.com/MattMcFarland/4c2f5cdd4657e91239cf7285b5d3b726

Use a script like that to launch the game (make sure to fix the -scriptlogfile by changing it to -scriptlogfiles). This will cause x4 to create some logs at:
Documents/Egosoft/X4/<random number>/<x4-game-datestamp.log>

and 

Documents/Egosoft/X4/<random number>/logs/mulesextended/supplymule-<ship-id>.txt

Start the game in debug, cancel the supply mule order, set it up again, and then pause and post the logs at that point.

**Comment by Chh2tx** [comment]
Infocenter is the only UI related one. https://www.nexusmods.com/x4foundations/mods/268

It has a few dependencies. 

I'll work on the logging.

**Comment by bhayden53** [comment]
infocenter and dependencies are very, very much a potential culprit. You can try disabling them in the main menu and see what happens. 

I would also recommend disabling JP's mods in that test as well.

**Comment by Chh2tx** [comment]
Finally was able to get back to this with the workday ending. The log for the ship in question appears to indicate the locked wares and then ultimately deciding to trade in energy cells -- as shown in the video.

Quite a few errors around in the overall log, but not sure of the importance of those.

[supplymule - okd-341.txt](https://github.com/Misunderstood-Wookiee/Mules-and-Warehouses-Extended/files/6246771/supplymule.-.okd-341.txt)
[x4-game-2021-04-01__17-26-09.log](https://github.com/Misunderstood-Wookiee/Mules-and-Warehouses-Extended/files/6246783/x4-game-2021-04-01__17-26-09.log)

I'll try disabling a few and see if that changes anything.

**Comment by Chh2tx** [comment]
No change disabling infocenter, and it's dependencies -- mod support APIs, and kuertee's UI extensions.

Testing with JP's off next.

[supplymule - okd-341.txt](https://github.com/Misunderstood-Wookiee/Mules-and-Warehouses-Extended/files/6246852/supplymule.-.okd-341.txt)
[x4-game-2021-04-01__17-50-45.log](https://github.com/Misunderstood-Wookiee/Mules-and-Warehouses-Extended/files/6246856/x4-game-2021-04-01__17-50-45.log)

**Comment by Chh2tx** [comment]
Not seeing a change with JPs disabled.

[supplymule - okd-341.txt](https://github.com/Misunderstood-Wookiee/Mules-and-Warehouses-Extended/files/6246875/supplymule.-.okd-341.txt)
[x4-game-2021-04-01__18-07-05.log](https://github.com/Misunderstood-Wookiee/Mules-and-Warehouses-Extended/files/6246876/x4-game-2021-04-01__18-07-05.log)

Going to keep toggling.

**Comment by Chh2tx** [comment]
Ok, so the only other mod enabled now is TaterTrader

That said, still seeing similar behavior. This one stalled for a bit at first, may be due to operations being fulfilled, so I tried something and added some shields to a station which created an energy cell demand. Immediately on doing so, the supply mule created an order to fulfill energy cells for the build storage, despite it not being a selected ware.

[supplymule - okd-341.txt](https://github.com/Misunderstood-Wookiee/Mules-and-Warehouses-Extended/files/6246949/supplymule.-.okd-341.txt)
[x4-game-2021-04-01__18-21-42.log](https://github.com/Misunderstood-Wookiee/Mules-and-Warehouses-Extended/files/6246951/x4-game-2021-04-01__18-21-42.log)

**Comment by Chh2tx** [comment]
Down to only Mules mod running. And for the first time out of all the attempts above, it actually preserved the 'specialWareBasket' when searching trades and didn't grab ECs from what I can see.

Unless I'm missing something else, it would seem to indicate that TaterTrader is conflicting with the 'specialWareBasket' in some way? 

[supplymule - okd-341.txt](https://github.com/Misunderstood-Wookiee/Mules-and-Warehouses-Extended/files/6247021/supplymule.-.okd-341.txt)
[x4-game-2021-04-01__18-52-49.log](https://github.com/Misunderstood-Wookiee/Mules-and-Warehouses-Extended/files/6246979/x4-game-2021-04-01__18-52-49.log)

Additionally, can confirm the EC demand is still there but the mule is appears to be properly oblivious to it in the logs.
![image](https://user-images.githubusercontent.com/47042057/113366364-9307dc80-931e-11eb-9549-c283bae7f4da.png)

**Comment by Chh2tx** [comment]
Well, re-enabled TaterTrader. Had trouble getting the High Tech fleet to do it again, but the Agricultural Fleet did similar thing.

It's locked to MREs, Med Supplies and Energy Cells, but it picked up Microlattice and Silicon Carbide and started trading Silicon Carbide. 

Does running multiple supply fleets perhaps interfere with each other in some way? Going to re-disable Tatertrade and see if I can get the two to do it again of it if only does it when TT is enabled.

[supplymule - pqi-830.txt](https://github.com/Misunderstood-Wookiee/Mules-and-Warehouses-Extended/files/6247083/supplymule.-.pqi-830.txt)

**Comment by bhayden53** [comment]
I've had Tater enabled in all my tests. 

Will start looking through the logs.

**Comment by bhayden53** [comment]
Ah, my apologies, I did actually miss that you were using fleets until I saw it in the first log and looked back to the last bit of your original post. 

Are your videos and the logs for a leader of a fleet of other ships with the mimic command?

**Comment by Chh2tx** [comment]
Yeah, always the leader. Can't set orders on the subordinates iirc.

Going to do some trials with it as the only addon again, in a fleet, not in a fleet, two mules, two mule fleets and see what I can replicate in just a few.

**Comment by bhayden53** [comment]
This could be a problem:

```
[=ERROR=] 329208.45 Error in AI script lib.request.orders on entity 0x36d9e: Property lookup failed: $object.defaultorder.id
* $object.defaultorder == null
* Expression: global.$mwex_AllMulesCommandTags.indexof.{$object.defaultorder.id}
```

This is not an area of the mod that I am particularly familiar with, but all of this code was PR'ed into our repo by the author of the Civilian Fleets mod. 

pqi-830 in the last log didn't have lock wares set, FWIW.

You'll be happy to hear that I am now able to reproduce the behavior when I have a ship set to mimic. I don't know the cause yet and I don't have the above error in my own log; but now that I can reproduce I should be able to figure out what's going on. Thanks for all the logs!

**Comment by Chh2tx** [comment]
Ah, my bad on the last. Surprised I only missed it once lol. I've been trying like hell to narrow it down all day cause it's been bugging the hell out of me.

**Comment by bhayden53** [comment]
ha, found it. really simple. I just forgot to copy the lock wares setting to the subordinates.

Why does that cause the commander to lose his lock wares setting? No freaking clue.

**Comment by bhayden53** [comment]
sorry I made you do all that work when it was my fault for not catching you were using fleets!

**Comment by bhayden53** [comment]
@Misunderstood-Wookiee https://github.com/Misunderstood-Wookiee/Mules-and-Warehouses-Extended/pull/113 addresses this issue and is ready for a minor release.

**Comment by Misunderstood-Wookiee** [comment]
> ha, found it. really simple. I just forgot to copy the lock wares setting to the subordinates.
> 
> Why does that cause the commander to lose his lock wares setting? No freaking clue. 

Bro.. 😆
I guess I'll update this later today 😇😅

**Comment by Chh2tx** [comment]
> sorry I made you do all that work when it was my fault for not catching you were using fleets!

No worries. I did a good bit during some conf calls since I'm wfh. Glad you were able to find it. Guessing the one that appeared to work correctly with TT disabled may have just been good timing on its part. I tried to keep things consistent with each attempt, including reloading the same save but it's easier said than done in a living world lol
