### ISSUE TITLE
Multiple station traders for wares set to internal only not working

### ISSUE THREAD

**Issue by Zerodaimaru** [Misunderstood-Wookiee/Mules-and-Warehosues-Extended#118]
If you assign more then one ship as a station mule to station with its wares restricted to the player faction only then only the first ship will find trades while the second ship will just sit there searching for trades. However if you don't assign them to the station or leave the wares unrestricted the mule will work as expected

Supply Station setup:
![image](https://user-images.githubusercontent.com/8076160/116768089-286fbc80-aa02-11eb-8a23-434de7179de5.png)

Warehouse Station setup:
![image](https://user-images.githubusercontent.com/8076160/116768173-a6cc5e80-aa02-11eb-8752-8604103f2c1c.png)

Station mule setup:
![image](https://user-images.githubusercontent.com/8076160/116768154-8a302680-aa02-11eb-8eac-855f209a8662.png)

With the above setup I've watched the first mule in the list make about 10 trips back and forth between the supply station and the warehouse station while the second ship hasn't made a single run.

**Comment by bhayden53** [comment]
What's the budget on the warehouse?

If there's any kind of connection between the two mules, it's happening somehow with the orders that the game is creating, and that's all deep inside the engine and out of modding territory. There is no way whatsoever for the mules to have any knowledge of each other.

**Comment by Zerodaimaru** [comment]
So by my own calculation both stations should have had more then enough credits to keep both ships going but for the sake of testing it I tried bumping each station up to 15 mil and that did in fact get both ships going. Not sure how the relates to some of the other effects I saw but the whole system around ware pricing for your own ships is confusing as anything. Apologies for the false bug report!

**Comment by bhayden53** [comment]
No worries; I agree that it can be very annoying. I think essentially what happens is that when the warehouse doesn't have "enough" funding (where "enough" is not something that we can really see or modify through modding), once a reservation is made for a ware, the warehouse shuts down all offers for that ware in order to keep funding available to buy other wares. That's the way the behavior looks to me, anyway.

**Comment by bhayden53** [comment]
It would be nice if it was smart enough to recognize player-to-player trades as "special", but that doesn't seem to be the case
