### ISSUE TITLE
[Potential Bug]: XML parse errors in debuglog

### ISSUE THREAD

**Issue by vlczero** [Misunderstood-Wookiee/Mules-and-Warehosues-Extended#125]
The commit e2f090649cbdc23605372a809df58eb06f6e7947 introduced some errors. From the debuglog:

```
[=ERROR=] 123376.38 extensions\Mules_and_Warehouses_Extended\aiscripts\station_mule.xml(422): Error while parsing expression: Operator expected
* Input: $targetIsResource and (not $targetIsProduct))
* Pos:                                               ^
[=ERROR=] 123376.38 extensions\Mules_and_Warehouses_Extended\aiscripts\station_mule.xml(423): Error while parsing expression: Operator expected
* Input: $(not targetIsResource) and ($targetIsProduct))
* Pos:    ^
[=ERROR=] 123376.38 extensions\Mules_and_Warehouses_Extended\aiscripts\station_mule.xml(425): Error while parsing expression: Operator expected
* Input: $targetIsWare and (not $targetIsResource) and (not $targetIsProduct))
* Pos:   
```
looks like double `))`

**Comment by Misunderstood-Wookiee** [comment]
Looks like it won't effect anything but debug, all those lines are debug
lines it seems.

**Comment by vlczero** [comment]
Yea thought so, Still learning x4 modding and what counts as not loading the whole mod. Had that problem with a typo in my own mod I'm making. Looks like bhayden53 already fixed it in efc7cb0e9f61f644e66416f0c679d127d9037472 

Closing this then. Thanks for the mod!

**Comment by Misunderstood-Wookiee** [comment]
Ah yes, and thank you for pointing this out too as it remind me that there
is a localisation pull request ill have too merge and fix the new param in
the commit that fixes this issue, as the localisation PR doesn't account
for this new parameter.


The fix you mentioned is available in the development branch as if speaking
I will most likely merge the localisation feature update and tidy up for a
public release today

**Comment by bhayden53** [comment]
I noticed this as well, I believe I fixed it in my local code but not sure if it made it into an actual pull request
