### ISSUE TITLE
Distrib Mule's cargo emptying routine spams log errors, doesn't work right

### ISSUE THREAD

**Issue by bhayden53** [Misunderstood-Wookiee/Mules-and-Warehosues-Extended#13]
Distrib mule needs a better cargo emptying routine if the script starts with cargo already in hold.

**Comment by bhayden53** [comment]
this is a mess, the other trade scripts I have for reference (random and tater trader) have really complex logic just for emptying cargo.

**Comment by bhayden53** [comment]
I worked on this a lot when I probably should have just done the blacklists, I want to get something good in there because a bad script will get a lot of traders blown up and take a lot of CPU time.

Will probably rip something from tater or random trader but those are full of custom variables that will take a while to sift through and make sure I have values for them.

**Comment by SM-Tiger** [comment]
why not just use the emptying routing from Supply Mule (that one worked fine for me, even though it didnt care at all for distance or my own stations.)
i.E. ship had 5.000 Superfluid Coolant
while right next to the ship was my own Complex that is looking for 40 k of that ware they would instead travel 10 Systems to sell 500 here, then another 5 Systems to sell 700 there xD (had it empty Cargo manually after i saw it flying round n round n round)

**Comment by bhayden53** [comment]
Replaced the cargo emptying routine in all mules with the routine from randomTrader in https://github.com/Misunderstood-Wookiee/Mules-and-Warehosues-Extended/pull/16

The different mules had more less the same cargo emptying routine. Needed one that obeyed blacklists and cared a bit about profits and didn't fail frequently. This one seems rock solid in my testing.
