### ISSUE TITLE
[Potential Bug]: find_buy_offer problem resp. Egosofts unlogic

### ISSUE THREAD

**Issue by ardelis-creech** [Misunderstood-Wookiee/Mules-and-Warehosues-Extended#134]
**Describe the Bug**
find_buy_offer don't find trades.
I try to transfer ore from a station to a warehouse (which is not possible with egosofts unlogic)
the only mule which possible can do this is distrimule, but the find_buy_offer logic is endless crap and sometimes he found a trade and sometimes he does not.
the egosoft crap hide trade offers just after the trade reservation 

**To Reproduce**
station (warehouse) with an buy and sell offer of the same ware
try to transport ware to that station with more than 1 transporter at the same time!

**Possible solution**

stop using find_buy_offer in scripts which uses static destinations
write your own logic which iterates over the targets and "manually" checks for free cargo space of specified ware.
the egosoft bullshit functions are not usable for such a usecase

**Additional context**

this 3 logs are all from the same time (with few seconds difference)
so no changing in the buy/sell setting at source/target station

miner 1

ScriptStart
gate distance from ship to source station: 9
source station #Sanctum Verge Factory
source station #Sanctum Verge Factory
this is the wareBasket
  [ware.ore]
these are the sell offers
  [trade.{0x86caL}]
  Ore 94875
these are the customers
  #Nopileos' Fortune VI Warehouse
these are all customer buy orders

miner 2

ScriptStart
gate distance from ship to source station: 1
source station #Sanctum Verge Factory
source station #Sanctum Verge Factory
this is the wareBasket
  [ware.ore]
these are the sell offers
  [trade.{0x86caL}]
  Ore 94875
these are the customers
  #Nopileos' Fortune VI Warehouse
these are all customer buy orders

miner 3

ScriptStart
gate distance from ship to source station: 3
source station #Sanctum Verge Factory
source station #Sanctum Verge Factory
this is the wareBasket
  [ware.ore]
these are the sell offers
  [trade.{0x86caL}]
  Ore 99675
these are the customers
  #Nopileos' Fortune VI Warehouse
these are all customer buy orders
  Ore 78
static storage setting value. If no source ratios are above this, no trades will happen
  0
  source cargo ratio for Ore: 99.675
  target cargo ratio for Ore: 0
found a trade: Ore 4800
supplyTarget for needFound2 block component #Nopileos' Fortune VI Warehouse

**Comment by bhayden53** [comment]
Both supply mule and Station mule will move mined wares. There is no chance that I will ever replace find_buy_offer with my own logic, as it will be a performance nightmare.

**Comment by ardelis-creech** [comment]
you don't have understand what the problem is.
the only way it work is with the "repeat order", but without the mimic support its not usable.

but its ok, i modify the scripts by myself.

**Comment by bhayden53** [comment]
mimic support has typically worked fine as well.

Are you saying mimic support doesn't work for the distribution mule?

I would strongly recommend you do not attempt to replace find_buy_offer; if you're seeing some issue I am nearly 100% certain that it can be fixed in a different way. If find_buy_offer is broken then every vanilla trade script would quit working, and it will be fixed in a future release. 

You're right that I still don't understand what the problem is you're seeing.

**Comment by Vectorial1024** [comment]
Chiming in; author of Civilian Fleets here

I do want to say that on my side of Civilian Fleets I have seen ppl reporting that the CivFleet just does not work [with the Mules] (cant copy orders), but I dont have the time/attention to confirm or fix it for the moment. Maybe it could be related to this? Because what I think I understand is that ardelis-creach saw that sometimes the mules work but sometimes they dont and when they looked at the scripts here, they began to think "maybe find_buy_offer is broken" and so ran some tests and believed that "find_buy_offer do seem to have bugged"

And yes do try NOT to redo what find_buy_offer is supposed to do. I agree sometimes EgoSoft's inbuilt "functions" are not 100% reliable but that is not a very good reason to just "do it by myself". There should be great performance nightmare for the game to read, understand, and execute the extra code that you might have decided to write to replace find_buy_offers.

**Comment by bhayden53** [comment]
@Vectorial1024 Do you have any good well-researched bug report I could look at? Some mules have certainly gotten a lot more attention than others for mimicking behavior, and I admittedly have not spent a lot of time making sure mules and civ fleets work together (especially after mimic was added to vanilla). I myself haven't kept up playing over the recent several months, so it's possible that various changes have accumulated that are now causing intermittent issues.

**Comment by Misunderstood-Wookiee** [comment]
Chiming in, the I pushed out all the code we had sitting around in PR pulls
not long ago one of them was a minbuy or min something civfleet fix for the
mimic behaviour no doubt there is probably more mimic options not being
carried over.

The other thing worth noting is the game has the ability to make a
warehouse officially now and has for some time.

**Comment by bhayden53** [comment]
Ah, you're right, I forgot you recently pushed an update that had changes from quite a while ago in there...

Hmm. Guess I'm going to have to fire up X4 soon and poke around.

**Comment by ardelis-creech** [comment]
hm my english must be worser than i thought....

to my initial problem:
the problem is, that if you have a station on which you buy AND sell a ware at the same time, egosofts unlogic remove the buy offer instantly if a reservation is added.

and what i saw so far, the buy offer comes back after the ware is completly sold.

thats why always only 1 transporter/miner can transport the ware to that station (warehouse), because after his ware reservation the buy offer is hidden

and thats why  find_buy_offer is crap and every mule script which uses that has the same problem.


mimic problem:
the only way to get such a system working is with the ingame "repeat order" feature.
but the repeat order feature does not work with mimic. so you have to manually add orders to all transporter/miners you want to use on the same route.


mimic works fine with mwe so far, but mwe uses find_buy_offer :)



but its ok, i changed the code of the distrimule, replaced find_buy_offer and now all miners on that route works as expected.


@Vectorial1024
"There should be great performance nightmare for the game to read, understand, and execute the extra code that you might have decided to write to replace find_buy_offers."
You know that a lot of movement features etc are written in that ugly script language?
I didn't wrote a functional identical replacement for find_buy_offer, i only wrote a replacement for the usecase in distrimule.

Greetings

**Comment by bhayden53** [comment]
Can you confirm how much funding is on the station that's showing this behavior? I have seen it before where buy offers do disappear after reservations are made, when the station does not have as much funding as it thinks it needs.

**Comment by bhayden53** [comment]
Also, can you make a fork of this repo and push your changes to distribution mule, just in case I decide to take a deeper look, as I'm curious what you came up with.

**Comment by Misunderstood-Wookiee** [comment]
Brian: Nope logic impossible won't do anything about it don't even touch
it.

Also Brian.

Brian: push us a fork I'm curious what was changed to look deeper.

😉 😝
