### ISSUE TITLE
[QUESTION]: I something to ask!

### ISSUE THREAD

**Issue by Inzann** [Misunderstood-Wookiee/Mules-and-Warehosues-Extended#135]
**I would like the know the following:**
Even with the pretty detailed description of what the different mules do I am having trouble understanding when to use which one.

Is there any reason I can't use only supply mules to fill my factories with supplies? I think I understood it that they should prioritize buying from your own factories first before looking for AI factories to supply.

Station mules as I understood it only go from one station to the other to supply while supply mules go from all your station to all your stations and then to AI stations if a ware can't be find in your stations.

I also see you can assign supply mules to specific stations and only those, isn't that just better then having a station mule?

**Comment by Misunderstood-Wookiee** [comment]
I mean we internally argued this same thing IRC, the only real use for
station mule is setting up warehouse factory though this is also
implemented into the vanilla experience now to a degree that is you can
finally make a station trade and store anything.

We don't remove station mule as it would simply infuriate the community who
prefer legacy mules but it does have some use cases where supply mule
isn't the best option.

Though,  trade mule,  distro and supply are about all I ever used.

**Comment by bhayden53** [comment]
The supply mule was not one of the original mules. The original author only wrote station, distribution, and travel mule. Station mule will actually also help out your other stations when his own station has no needs.

I personally find that station mules are less likely to get "distracted". i.e. they are good at filling urgent needs or emptying full storage. Supply mules are best for filling out inefficiencies; i.e. finding the cheapest supply from the AI for something you're not producing yourself.

In practice, what I usually do is approximately 1 medium station mule and 1 medium supply mule for each factory with ~2k workforce. Enough travel mules on the warehouse just to keep income flowing without emptying my stock too much. I do not use distribution mules at all.

**Comment by Misunderstood-Wookiee** [comment]
I remember because I merged the supply mule early on before you came into
assist then the scope grew with re coding 😝.

I dunno we play differently see I focus more on dog fights so I just want
income flow I usually let the AI handle moving stuff around whatever helps
remove me having to micro stations usually is better for me personally.

That is maybe why I use the supply mule more I don't setup anything for max
efficiency it just has not run at a loss or stall

**Comment by Inzann** [comment]
Thanks for the replies guys! Thought I was missing something. :D

**Comment by draeath** [comment]
> the only real use for station mule is setting up warehouse factory though this is also implemented into the vanilla experience now to a degree that is you can finally make a station trade and store anything. We don't remove station mule as it would simply infuriate the community who prefer legacy mules but it does have some use cases where supply mule isn't the best option. Though, trade mule, distro and supply are about all I ever used.

@Misunderstood-Wookiee in the description text on the nexus, workshop etc the station mule has this text in it:

> These Mules were the first in the Family, and should be your most numerous ones.

I suggest editing or removing the second part of that sentence. It suggests to someone new to this extension that we should be making heavy use of them, which seems contrary to what you say here in this issue.

**Comment by bhayden53** [comment]
I disagree with Wookiee on that one, I still use a ton of station mules

**Comment by Misunderstood-Wookiee** [comment]
Now now, each to one's own. It depends ok how you play the game if you
really think about it.

I mostly front line the war in a cockpit the eco side I usually setup some
basic supply for cash flow to pup fleets and then I'm off too the races the
Ai can sort their own economic issues out 🤣

**Comment by bhayden53** [comment]
I shouldn't have used "disagree", was just pointing out that there are indeed many ways to have success with the mules, and that mine definitely still includes a lot of station mules.
