### ISSUE TITLE
[Potential Bug]: Station mules trading loop at same station

### ISSUE THREAD

**Issue by Padimm** [Misunderstood-Wookiee/Mules-and-Warehosues-Extended#136]
>Please check for an existing issue before making a new report and comment in that report if one exists.

**Describe the Bug**
All my station mules are buying and selling wares at the Warehouse. For example they buy 4k field coils from the WH then sell the same back immediately. All my station mules are doing this and hence not moving needed items to build stations and produce wares in said stations. Never seen this before my current play a couple days ago

**To Reproduce**
Steps to reproduce the behaviour:
Just by setting up a Station mule to trade between a station and a waerhouse

**Expected Behaviour**
I was expecting the mules to be moving items between stations, but instead they just constantly buy and sell to the Warehouse and never move items to other stations.

**Version Info (please complete the following information):**
 - X4 Foundations : Current public release
 - Mules Extended Mod : 6.3.6
 - I downloaded the mod from: Nexus

**Screenshots**

![20211130101728_1](https://user-images.githubusercontent.com/54664083/144136834-0a408bf2-d9ea-4ce8-93d7-386cf60610e8.jpg)

![20211130101715_1](https://user-images.githubusercontent.com/54664083/144136862-b6083339-bb76-45e8-aa4c-c3ee42c1fbc7.jpg)

**Additional context**
Any assistance will be greatly appreciated. I only really use the station mules to keep the drone requirement in the logistical overview maintained as the stations finish modules.

**Comment by bhayden53** [comment]
Could you screenshot the warehouse logical overview?

**Comment by Padimm** [comment]
Hi bhayden and others,

I had the same thought re WH orders and once I changed all of them from Auto buy/sell amounts it seems to have resolved.

Thanks for your rapid response!
