### ISSUE TITLE
[QUESTION]: component supply trades issue

### ISSUE THREAD

**Issue by Padimm** [Misunderstood-Wookiee/Mules-and-Warehosues-Extended#137]
Hello clever people! I have a question. It seems to me the resources needed to stock drones on stations to take forever and I usually have to manually buy the drone comps/energy cells/smart chips.

Which mule does this function? I never seem to see supply mules doing these trades...

Thanks in advance

**Comment by Padimm** [comment]
Still seem to have this issue. The Supply mule function never seems to give the 3 components required to stock drones, being Drone Components, Smart Chips and Energy Cells.

Any ideas?

**Comment by bhayden53** [comment]
Do you have any default "supply" trade rules? The "supply" trade rules cover these kinds of components.

**Comment by Padimm** [comment]
No default rules. I have amounts manually selected; only price is default
