### ISSUE TITLE
missing icons

### ISSUE THREAD

**Issue by bhayden53** [Misunderstood-Wookiee/Mules-and-Warehosues-Extended#14]
error message:
[=ERROR=] 139947.30 c:\dev\p1\src\X4\universe\holomap.cpp(5942): Could not find mission order icon order_distrimule [Lino]
(version: 3.10 - Code revision: 394044)

**Comment by Misunderstood-Wookiee** [comment]
Simple -
Need to add an icon to each order I will use a vanilla icon from the game for each mule order. 
Likely the ware basket the traders use for auto trade.

**Comment by Misunderstood-Wookiee** [comment]
Fixed in https://github.com/Misunderstood-Wookiee/Mules-and-Warehosues-Extended/commit/a2b765c8c1e958b19689c7e2119c83acfe74c308

If it occurs again re-open
