### ISSUE TITLE
[FEATURE]: Ignore Assign Ship To Station for Mimic

### ISSUE THREAD

**Issue by satheon49** [Misunderstood-Wookiee/Mules-and-Warehosues-Extended#141]
**Describe the solution you'd like:**
When assigning ships to a station it would be nice to be able to assign additional ships with "mimic behavior". However the commander is immediately changed to the station because it is part of that behavior.

**Reproduction**
* Select ship 1 
* Choose M4 - Supply Mule and tick assign ship to station
* Select ship 2
* Mimic ship 1 behavior
* IS: ship 2 is removed from ship 1 fleet and assigned to station
* SHOULD: ship 2 should remain in ship 1 fleet

**Comment by Vectorial1024** [comment]
Quite related to #138 so maybe we have something extra to think about.

**Comment by bhayden53** [comment]
wonder if it's as simple as forcing the value of assignHome in this block?
https://github.com/Misunderstood-Wookiee/Mules-and-Warehouses-Extended/blob/069f31c8e78b8d5b1b7fb55bff6606b7cee71234/aiscripts/supply_mule.xml#L201

**Comment by bhayden53** [comment]
So I just realized that the patch of order.assist.xml is actually where mimic functionality for the mules occurs:
https://github.com/Misunderstood-Wookiee/Mules-and-Warehouses-Extended/blob/Dev/aiscripts/order.assist.xml

edit: we used to have logic to directly transfer params in the mules aiscripts. I must have stripped them out in the past.

**Comment by bhayden53** [comment]
merged to dev, should be in next release (hopefully in the next few days)
