### ISSUE TITLE
[FEATURE]: Separate build storage cargo capacity

### ISSUE THREAD

**Issue by satheon49** [Misunderstood-Wookiee/Mules-and-Warehosues-Extended#146]
**Describe the solution you'd like:**
"Fill Cargo Hold %" is a useful feature to prevent mostly empty runs. However when fulfilliing buy offers from player owned build storages it would be better if such an order would be completed instead of simply ignoring it for all eternity.

I suggest a new value "Player build storage cargo mod" (with a better name) with default 100 that acts as a percent modification to "Fill Cargo Hold %". For example setting FCH to 75% and the new one to 50 means Build storage offers must only fill up to 37.5% of cargo space.

**Describe alternatives you've considered:**
A simple boolean flag instead of another slider that disables the "Fill Cargo Hold %" check for player owned build storages. However at worst it would mean an Incarcaruta deliver 300 energy cells.

**Additional Context (if any)**
The only way with the current version that ensures that build storage is served is buy setting "Fill Cargo Hold %" to 0. Such a trader would either sit idly a lot (if you only use it for build storage) or would do insanely inefficient normal trades (basically rushing to every station that completes a single production cycle).

**Comment by bhayden53** [comment]
The supply mule is supposed to ignore the cargo hold slider if the trade is for build storage and would finish off the ware. Is that not working?

**Comment by satheon49** [comment]
I am pretty sure it does not work, but I will try to test it again under controlled conditions and report back.

**Comment by bhayden53** [comment]
The second clause of this if statement should let the build storage trades through:
https://github.com/Misunderstood-Wookiee/Mules-and-Warehouses-Extended/blob/eef767121a549f7405c6ba248465043139516a80/aiscripts/mule.lib.evaluate_tradeoffers.xml#L135

**Comment by satheon49** [comment]
What is $targetOfferedAmount in this case? If it is the volume required by the build storage wouldn't that mean that this check only every returns true if the amount offered by the source is exactly the amount required by the target?

**Comment by bhayden53** [comment]
Yes, but if the amount were bigger, then it wouldn't get clipped by the $minCargoSize check.

Wait, oh shit, is there a scenario where the trade finishes off the build storage but is bigger than $minCargoSize and so we have a False and False?

**Comment by bhayden53** [comment]
I will have to think through the logic, but I am heavily distracted at the moment. I will try to think through it later today.

**Comment by satheon49** [comment]
Ok and I will test it ingame again as soon as I have enough money in my current game.

**Comment by bhayden53** [comment]
It does "feel" like something looks wonky in the if statement but I can't quite put my finger on it without sitting down and writing out a truth table

**Comment by satheon49** [comment]
I tested it in game and it did not work
Scenario: 
- HQ with small dock queued
- buy offers 185 hull parts at 274 Cr. Assigned Vulture Vanguard is just sitting there even with in system sell offers that are below buy offer price (880 hull parts for 260 Cr sell offer)
- assigned a Courier Vanguard with Fill Cargo Hold % at 25% and it still did not complete the trades

I took a look into the code and the code you mentioned and I believe it is working correctly:
`and not ($buyoffer.buyer.isclass.buildstorage and ($tradeAmount == $targetOfferedAmount))`
$tradeAmount is what we want (or can) trade for, minimum out of affordable, maximum of what we want to buy and available space, targetOfferedAmount is what we want to buy.
Pick hull parts in above case.  Trade amount in that case is 185 (because 185 is the lowest out of what we want, our cargo space (10200) and whatever is affordable).

I think the problem is from restricting station construction trades to your own faction (which I activated so the AI would not snatch up the trade offers while I did my test). The trade is skipped if either the buy or the sell offer is faction restricted. In this case the sell offer was Teladi which was not allowed to fulfill the buy offer of my station.

I am unsure whether this is a bug or a feature. On one hand I understand that you might not want to trade with a specific faction at all in which case it makes sense to apply the restriction to the SELL offer as well as your stations buy offer. But on the other hand that makes it impossible to prevent the AI from fulfilling your build storage buy offers while still allowing your ships to buy wares at the lowest possible price.

**Comment by bhayden53** [comment]
Ah, yes, the supply mule does indeed check the trade rules and it will block trades where it goes out to buy from a faction that you don't allow. I am not really sure any way around that. I don't think ignoring trade rules is the right solution as people will think that's a bug. 

One thing you could do; if you have a warehouse, you could set the ware up there, have a mule sourcing it at the best prices, and then your build storage mule will be able to pick up from the warehouse. A simple warehouse is very cheap to initially set up, and you can add to it over time to turn it into a trade station.

**Comment by satheon49** [comment]
Thanks. I think I was not expecting the build storage trade setting to act that way. I even double checked with a vanilla build storage trader and he acts the same way i.e. not finding trades as long as a faction restriction is in place for build storage trade.

Anyway, my initial assumption was wrong and even the reason why it did not work for me was intended behavior so I am closing this. Thanks again!

**Comment by Misunderstood-Wookiee** [comment]
I should maybe add that tid bit to the readme for the buid storage

**Comment by Misunderstood-Wookiee** [comment]
Was going to say a aimple ignore build storage check box would probably
resolve this.
