### ISSUE TITLE
[Potential Bug]: I think I found a bug!

### ISSUE THREAD

**Issue by 007Psycho007** [Misunderstood-Wookiee/Mules-and-Warehosues-Extended#148]
>Please check for an existing issue before making a new report and comment in that report if one exists.

**Describe the Bug**
The Supply Mules ignore Energy Cells. Everything else works as intended

**To Reproduce**
Steps to reproduce the behaviour:
1. Set up Supply Mule as follows: 
![image](https://user-images.githubusercontent.com/24194327/149668940-5473c15e-8e5b-4267-9b40-e21d27e4a1a8.png)

2. Wait for Mule to start trading.. which he doesnt. It also didnt work when assigning the mule to the Sector instead of the station. All other wares are handled by mules perfectly fine. 

**Expected Behaviour**
Mule should start moving energy cells.

**Version Info (please complete the following information):**
 - X4 Foundations : 4.20
 - Mules Extended Mod : 6.40
 - I downloaded the mod from: Workshop

**Screenshots**
See above

**Additional context**

**Comment by Misunderstood-Wookiee** [comment]
Can you run the debug and attach the log files it creates?  Add the follow
to the games launch parameters (you can do this through Steam)
 -debug all -logfile debuglog.txt

**Comment by bhayden53** [comment]
I currently have 15 incoming energy cell trades from supply mules at my warehouse...

Things to check here:
- Do you actually have player supply for energy cells (and within 3 jumps)?
- if you lock the ware to something else, does that work (i.e. testing the lock ware function)?

If you can't figure it out, I'll need a debug log. Instructions in this post:
https://github.com/Misunderstood-Wookiee/Mules-and-Warehouses-Extended/issues/98#issuecomment-714633061

**Comment by 007Psycho007** [comment]
Weird. Now they are hauling energy cells. Dont know what happened but I take it. Issue can be closed. Sorry for bothering you guys.
