### ISSUE TITLE
better debug messages

### ISSUE THREAD

**Issue by bhayden53** [Misunderstood-Wookiee/Mules-and-Warehosues-Extended#15]
There are various debug_to_file messages laying around from my attempts to understand the code and get everything working right. These should be condensed down into a smaller number of messages and made more useful.

**Comment by Misunderstood-Wookiee** [comment]
Does this resolve #7 ?

**Comment by bhayden53** [comment]
Similar to the logbook issue that I closed, all of the mules have had significant improvements to debug logging, and further work should go into a new issue.
