### ISSUE TITLE
[Potential Bug]: Station mules cant transport the same ware, if assigned to station.

### ISSUE THREAD

**Issue by Skharr** [Misunderstood-Wookiee/Mules-and-Warehosues-Extended#152]
**Describe the Bug**
If you assigned two station mules and checked the "assign Ship to Station" then the second mule cant transport the same ware if the first one already on it. If you uncheck the "Assign ship to Station" then everything works as expected.

**To Reproduce**
Steps to reproduce the behaviour:
1. Assign two "Station Mules" to a Station. 
2. Check the "Assign ship to Station"
3. Let them both run the same type of ware.
4. Only the first one is transporting the ware. The second one is waiting for work.

**Expected Behaviour**
Two station mules can transport the same ware at the same time, even when the station mules are assigned to the station.

**Version Info (please complete the following information):**
 - X4 Foundations : 4.20
 - Mules Extended Mod : last one from Nexus
 - I downloaded the mod from:  Nexus

**Comment by bhayden53** [comment]
This has nothing to do with mules, and is due to the way station managers allocate funding for trade offers when reservations already exist (even when no money is actually exchanging hands). The best thing you can do is make sure everyone has all of the funding they're asking for.

**Comment by Galaxy-Spam** [comment]
I tend to agree with @bhayden53.
Can you quickly check the money and the current trade offer (after the first mule has its job)?

**Comment by Skharr** [comment]
200k station account and about 1kk warehouse. The sell order is lowest price and the buy order is highest price at my warehouse

**Comment by bhayden53** [comment]
station mule doesn't care about price at all, and I have seen this a million times, where any reservation at one of the stations blocks other trades from being reserved

**Comment by Skharr** [comment]
Ok. Yeah then sad, nothing to do about it. I changed my setup to supply mules and ordered them to do only one type of ware. It works too, its only a different way

**Comment by Galaxy-Spam** [comment]
i will check and provide a fix. That does not seem  right.

**Comment by Misunderstood-Wookiee** [comment]
This game is full of surprises.
You'd think the Devs would make the economic system be more robust than
this there seems to be gotchas at every turn.

**Comment by bhayden53** [comment]
I suspect that since "assign ship to station" is involved, it's almost entirely due to reservations on the assigned station causing the order not to appear, due to funding. 

The raw amount of funding is completely irrelevant, all that matters is how much funding the station has vs how much it is requesting. If it is not 100% full, there is a chance that a reservation for a ware will cause the manager not to offer any more trades for that ware, in order to keep funding available for reservations for other wares.

**Comment by Galaxy-Spam** [comment]
So, i just did a test. For me it works perfectly fine. 
I uploaded a savegame with my test setup.
Extensions are: cheat_menu + mules

https://drive.google.com/file/d/1KQw-b4yqi13s_5dXpnhj4ir9Dp98uJtF/view?usp=sharing

Can someone double check or give me a case that actually does not work?
