### ISSUE TITLE
[Potential Bug]: Supply mule supplying AI instead of player

### ISSUE THREAD

**Issue by Derinzed** [Misunderstood-Wookiee/Mules-and-Warehosues-Extended#154]
The Supply Mule appears to be supplying AI stations and not my own when their home is designated as a sector.

**To Reproduce**
Assigning a supply mule to sector causes them to supply build storage of AI stations instead of players

**Expected Behaviour**
The supply mule should supply the player's station

**Version Info (please complete the following information):**
 - X4 Foundations : 5.0
 - Mules Extended Mod : Latest
 - I downloaded the mod from: Steam

**Comment by bhayden53** [comment]
Can you post a debug log for a mule in this sector that's causing problems? Instructions here:
https://github.com/Misunderstood-Wookiee/Mules-and-Warehouses-Extended/issues/98#issuecomment-714633061

**Comment by Derinzed** [comment]
Hello,

Thanks for the reply. I followed the instructions and launched the game from the bat file (as administrator). I assume it works as I can see the fps counter now, but no logs are generated in Documents\egosoft\X4\<Number> other than the debug.log.  There is also no other sub folder for logs pertaining to the mules.  I did do a bit more testing.  It functions if I allow the mule to gather from player, but if I disable that feature they take a long time to find trades (20+ minutes) and then serve the AI.

**Comment by bhayden53** [comment]
Hi,

Note in the linked comment that there's an edit you have to make to the bat script, as it has a typo. Did you make that edit?

**Comment by Derinzed** [comment]
Ah, Yes, that was it! Thank you!

Here is the log and an image showing my current configuration for the trader.  It should be noted, I have no stations in the sector where the trader is ultimately attempting to supply a build storage.

[supplymule - qvt-001.txt](https://github.com/Misunderstood-Wookiee/Mules-and-Warehouses-Extended/files/8308735/supplymule.-.qvt-001.txt)

![supply](https://user-images.githubusercontent.com/45581121/159110605-1ccb9538-2aa6-4c46-ae90-397c69e4b953.jpg)

**Comment by bhayden53** [comment]
Thanks. Which station in the log file is yours?

**Comment by Derinzed** [comment]
I don't think that there is any reference to any of my stations in that log file.  I assigned the trader to a sector (with a wide number of jumps from home), and told it to not take any resources from my stations.  My goal is to allow these traders to supply my various shipyards around the galaxy, and supply my other station's build storages. but based on both the game and log (from what little I looked through it), they never consider my stations, only the AI stations.

**Comment by bhayden53** [comment]
hmm. could you try checking "collect from player". The text on that was modified recently and I'm wondering if it's not an accurate portrayal of that option anymore.

**Comment by Derinzed** [comment]
I can try checking it again tomorrow. Is there anything specific you want me to try with that? from my testing today, with it enabled the traders will supply my stations but pull from my other stations (as expected).  Of course, it creates a problem when the traders pull from my shipyards to build other stations haha, which is why I'm trying to get it to not pull from my stations.

**Comment by bhayden53** [comment]
I suspect that the option is simply mislabeled now and that by having it unchecked it is filtering out all of your stations buy orders.

Essentially there is no way to filter between buying from the player and selling to the player; you can either turn all player trades on or off.

The way to stop your mules from buying from your shipyards would be to turn off the sell orders at the shipyards in the logical overview.

@Misunderstood-Wookiee it looks like "collect from player" is misleading, as it also turns off selling to the player.

**Comment by Derinzed** [comment]
ok, so it's working as intended, I just misunderstood the function?  So that is supposed to disable all player consideration as opposed to buying from AI to sell to player?  I would assume then that the respective AI option does the same for the AI where is disables all AI consideration?  

Thank you BTW for your assistance.

**Comment by bhayden53** [comment]
Yes, the text used to be something different but it got changed during a localization attempt, I believe. I think it is now labeled in a misleading way. So it's not really your fault, what the text implies is the wrong interpretation of how the setting works.

**Comment by bhayden53** [comment]
I think I would suggest that the text is changed to:
"Allow Player Trades"
"Allow AI Trades"

**Comment by Derinzed** [comment]
Yeah, that does sound like a better representation of the option.  If I might also suggest, the readme also seems to imply that the option only restricts the supplying faction.  Perhaps taking what you just explained to me and putting it there might also be helpful to people in the future.

**Comment by Misunderstood-Wookiee** [comment]
> I suspect that the option is simply mislabeled now and that by having it unchecked it is filtering out all of your station's buy orders.
> 
> Essentially there is no way to filter between buying from the player and selling to the player; you can either turn all player trades on or off.
> 
> The way to stop your mules from buying from your shipyards would be to turn off the sell orders at the shipyards in the logical overview.
> 
> @Misunderstood-Wookiee it looks like "collect from player" is misleading, as it also turns off selling to the player.

I was well aware of this.
Those two options remain functionally the same as they ever were.. Turning one-off turns off the logic even looking at the player for wares period..

Being an accurate description is subjective IMHO, 'Collect From Player' implies to me at least that the logic will collect anything from the player. I believe a very simple fix can be done to clean up the interpretation. 




> I think I would suggest that the text is changed to: "Allow Player Trades" "Allow AI Trades"

The 30s to implement that and 5min to execute an update, we did not really confirm what was best the last time I wanted to do a wording pass on the parameters. 

_May suggest ..._
**Include Player Trades**
**Include AI Trades**

As I feel **Allow** implies something else when we are including own and faction into our mule search result logic. I am happy with either, will wait for the response on this and go ahead and make the changes. I will close this issue personally after relating the cleaner worded update.

**Comment by Derinzed** [comment]
Hello, 

Thank you for replying!  I personally like "Include Player Trades"  It sounds more like a faction filter rather than a feature that I'm disabling.  

Final question on my part if I may. So if I want traders to buy from AI to sell to me, I need to have both options enabled, and restrict my stations to not sell to myself (so they don't just distribute wares)?

**Comment by Misunderstood-Wookiee** [comment]
If you want mules too buy from Ai factions aswell as player in regard too
supplying your own stations  yes, you need to enable both.

**Comment by Misunderstood-Wookiee** [comment]
Further pondering  after rereading my own wording  how do we feel about...

**Include from Player**
**Include from AI**

IMHO this leaves no room for interpersonal  interpretation as it no longer sounds like selling  is even what it would do.

**Comment by Derinzed** [comment]
Well, that's the thing. I don't.  I want to have my supply mules buy from AI to sell to my stations. When I disabled the "Collect from player" option the supply mules only sold to AI stations, and never mine.  Which I thought was a bug, but now I think both of you have pointed out that those options disable the selling too?

**Comment by Misunderstood-Wookiee** [comment]
Well I'm confused...
Supply mule should never be selling to AI under normal circumstances regardless what you select. 

It will do so only in odd circumstances such as the trade is no longer valid but it has that ware in its cargo it instead will attempt too sell it back at average market value but the inner workings of that is it kind of just deletes the cargo and gives the player equivalent  market value in return. 

Irc that is how  handled supply mule getting rid of cargo safely if the buyer suddenly doesn't want it any more . 

It never should be actually  buying from player to sell to ai.


I've seen this kind of issue before as you suggest when tick both it buys from player sells to Ai it appears that way but instead what probably happens is it buys from player to serve a station owned by player but then that need gets filled before the mule finished the trade then it gets a new order doesn't have space for the order so it has to go sell the cargo to an ai station to free up cargo space. 

Is what I think happens but the other guy would know more about it than me 

To verify and confirm, the supply mule should still sell to the player as defined in your parameters the player and ai factions options just toggle buying from those sources.

**Comment by Derinzed** [comment]
yeah, it seemed odd to me too. I posted a log of a mule performing this odd behavior, as well as an image of how I had it configured. The mule bought from AI and was going to sell to AI. As I noted with the log, the mule was selling in a sector that I owned no stations, so it was to the AI and not to me.  It did the same thing across all my mules.  I believe it all worked well until 5.0, which is when I started noticing that things weren't working correctly.

**Comment by Misunderstood-Wookiee** [comment]
Hmm I did wonder If the 5.0 would break anything  due EgoSoft changing how
trades work a little bit. I dont believe we have conducted full testing
ourselves yet.

The supply mule definitely shouldn't have done that.

**Comment by bhayden53** [comment]
> Supply mule should never be selling to AI under normal circumstances regardless what you select.

This is not true.

**Comment by bhayden53** [comment]
There is nothing broken here except the wording of the params.

**Comment by Misunderstood-Wookiee** [comment]
Does the supply mule sell to the ai how they describe it is from buying
from ai then selling directly to the Ai supplying  the ai station owned? I
didn't think it did that.

**Comment by bhayden53** [comment]
After @Galaxy-Spam 's re-factor, when the supply mule is assigned to a sector it first prioritizes the player in each loop, but is allowed to fulfill AI orders if the "collect from AI" box is checked. We misinterpreted what galaxy meant by "allow ai suppliers" when we changed the text during localization.

**Comment by bhayden53** [comment]
It's the same thing for the player trades, by unchecking that "collect from player" box it removes all player factions from being serviced.

**Comment by Derinzed** [comment]
I spent some time debugging today and I think I fixed it (though I would still like to do some testing).  It looks like this line with the brackets didn't allow the faction to be properly assigned to the variable, meaning it was effectively empty later on in the code: 

(Line 173)

<set_value name="$playerFactions" exact="[faction.player]"/>

I changed that to:

<set_value name="$playerFactions" exact="faction.player"/>

So far it has fixed it for me.

Through testing, when that was in its original state, the variable was literally: [faction.player], instead of the actual faction name.  and once line 348 executed it changed the variable $playerFactions to an empty table ([]).  

So, again, I think that by removing those brackets everything is fixed, but I've only got an hour or so of playtime in since making that change.  But it is functioning as described, where the mule will purchase from only the AI and sell to my stations.

**Comment by bhayden53** [comment]
hmm I don't think that should work. What I've been looking at is L330. That is a direct usage of the check box, and if it's not checked, it removes the player priorities from the table, so that it doesn't look for buy offers from player stations.

**Comment by bhayden53** [comment]
ah, and maybe here I am misinterpreting the variables as well. Let me think about it a little more.

**Comment by Derinzed** [comment]
yeah, I also added a few debug lines, so line 348 isn't actually the line I meant. hang on

**Comment by Derinzed** [comment]
yes, line 330. that was what I meant. at that line the variable would become an empty table, but even before that, it was never really defined as the player faction.  If you print the variable to a debug log right after assigning $playerFactions, it'll print as "[faction.player]". and once you hit line 330, it'll become [] (empty).  if on line 173 you change it to be the literal "faction.player" (without brackets) it will be the actual faction, and will not be returned empty at line 330.  to be completely honest with you, I'm not sure why [faction.player] becomes empty on line 330, but it does, and without the brackets, it retains its value.

**Comment by bhayden53** [comment]
Yeah I can't figure out why it would be blank either. But I also suspect that the variable is really supposed to be a list and that by initiating it otherwise it will cause some other problems.

**Comment by bhayden53** [comment]
It's really the value of $serveFactions that should matter and where it's printed in the logs it is [faction.player] and that should be perfectly fine, I think.

**Comment by Derinzed** [comment]
ah yes, sorry, that's the variable that becomes blank.

is it possible the variable is being initialized as literal text instead of a list?

**Comment by Misunderstood-Wookiee** [comment]
> the

I honestly had no idea it ever got changed to that functionality.  Explains a lot. 

Okay so now I understand better  

We need
Supply Player
Supply AI 

?

**Comment by Derinzed** [comment]
I don't think so.  Looking over the code, it really does look like the text in place now truly represents what is going on.  It looks like those two options only toggle where the supplies come from, not where they go to.  all the sell order searches filter based on those parameters, so frankly, I wouldn't even bother changing it.

**Comment by bhayden53** [comment]
I'm trying to see now if there actually is a bug somewhere. 

Didn't you say that checking the box caused the ship to start finding the trades for your stations?

**Comment by Derinzed** [comment]
yes, only when the "collect from players" box is checked will it sell to my stations.  but that doesn't fit with what the code describes.  based on what I'm seeing the only thing that should change when that parameter is disabled is where the supplies come from, not who they are sold to.  What does affect where they are sold is the $serveFactions variable, which gets toggled based on $isServingPlayer, which itself is toggled by where the player assigns the mule.  The player can assign the mule to an AI station or ship, and that will toggle $servingFactions to $aiFactions, otherwise it will be $playerFactions, which Is where I think the bug is.

**Comment by bhayden53** [comment]
Ah! I know why $serveFactions is becoming a blank list

Look at the md guide here:
https://www.egosoft.com:8444/confluence/display/XRWIKI/Mission+Director+Guide#MissionDirectorGuide-listsLists

Under the section on lists:

> Lists are stored in variables as references, so multiple variables can refer to the same shared list: If you change a shared list through a variable, e.g. by changing the value of an element, you change it as well for all other variables. However, the operators == and != can also be used on two distinct lists to compare their elements.

At L273 we have this:

`            <set_value name="$serveFactions" exact="if ($isServingPlayer) then $playerFactions else $aiFactions" />
`

So $serveFactions is being set to a reference of $playerFactions.

At L310, we then add that to the table:
`                <append_to_list name="$prioritylist" exact="table[ $supplierFactions = $playerFactions, $serve = 'area', $type = 'buildstorage' ]" />
`

And so $priority.$supplierFactions is also a reference to $playerFactions.

Then at L330 we hit this:
`                <remove_from_list chance="100*(not $allowPlayerSuppliers)" name="$priority.$supplierFactions" list="$playerFactions"/>
`

And so because $allowPlayerSuppliers is not checked, and because $serveFactions is a reference to $playerFactions, we actually remove player.faction from the underlying list for both $serveFactions and $priority.$supplierFactions. We meant to just remove it from $priority.$supplierFactions.

**Comment by Derinzed** [comment]
Ah! there we go, nice find!  yeah, that would certainly do it.

**Comment by bhayden53** [comment]
So now I just need to figure out the way to get around the referencing issue introduced in L273.

**Comment by Derinzed** [comment]
the first two things that comes to mind are to either:

1: do it explicitly and create the lists when you set them on L273, or
2: create new variables just for them to be set there.

granted, option 1 is kind of ugly looking.

**Comment by bhayden53** [comment]
I didn't originally write most of this version of the code, but I wonder why we can't just do:

`            <set_value name="$serveFactions" exact="if ($isServingPlayer) then [faction.player] else $aiFactions" />
`

But, L331 is almost certainly also bugged if you uncheck the ai box, so I think I need to find a solution for how to make a copy of a list instead of a reference.

**Comment by bhayden53** [comment]
I'm wondering if the .clone property of a list will work,  the md guide says it makes a shallow clone, so any nested lists would still be references. But perhaps the rest of the list will be true copies. Guess I have to fire up the game now

**Comment by Derinzed** [comment]
I almost think that you would have the same issue with references.  You could also do this:

            <get_factions_by_relation relation="dock" result="$aiFactionsServing" object="this.ship"/>
            <remove_from_list name="$aiFactionsServing" exact="faction.player"/>
	        <set_value name="$playerFactionsServing" exact="[faction.player]"/>
			
            <set_value name="$isServingStationOrShip" exact="if ($homeStationOrShip != null) then true else false"/>
            <set_value name="$isServingSector" exact="if (($home.isclass.sector and $dedicatedServe) or ($home.isclass.{[class.ship, class.station]} and not $dedicatedServe)) then true else false"/>
            <set_value name="$isServingPlayer" exact="(not $isServingStationOrShip) or ($homeStationOrShip.owner == faction.player)" />
            <set_value name="$serveFactions" exact="if ($isServingPlayer) then $playerFactionsServing else $aiFactionsServing" />
            <set_value name="$isServingArea" exact="$isServingPlayer and (not $dedicatedServe)" />
            <set_value name="$isDedicatedPlayerBuilder" exact="$isServingPlayer and $allowBuildstorage and (not $allowResources) and (not $allowIntermediates) and (not $allowTradewares)" />``

it's not all that elegant, but would avoid the reference.

**Comment by bhayden53** [comment]
Yeah I see what you're getting at. I'm going to try clone first and then I'll fall back on totally clean variables if it doesn't work.

**Comment by Derinzed** [comment]
sounds great.  Please do let me know if the clone works, I'd be interested to know how that plays out.

**Comment by bhayden53** [comment]
changing L273 to:
`            <set_value name="$serveFactions" exact="if ($isServingPlayer) then $playerFactions.clone else $aiFactions.clone" />
`

Seems to work for me. I don't have any buildstorage in my area right now, but, before making the change, if I uncheck Collect from Player, my supply mule tries to trade with an AI buildstorage 3 sectors over. After adding the clone in, it finds a trade for my wharf in the same sector.

**Comment by Derinzed** [comment]
that sounds like it worked then!  very nice!

**Comment by bhayden53** [comment]
addressed by https://github.com/Misunderstood-Wookiee/Mules-and-Warehouses-Extended/pull/155

sorry @Misunderstood-Wookiee for earlier, I was wrong that there's no bug. Glad you guys were persistent in getting me to look deeper.

**Comment by Misunderstood-Wookiee** [comment]
That's all good 👍 .

I was going to say i was wondering why it was doing what it did when the
language  just sat collect from AI or player which makes sense as the code
does just that there aren't any explicit sale parameters

**Comment by Misunderstood-Wookiee** [comment]
Mules Version 6.4.2 issued fixes in #155 
Build released to public sources.
