### ISSUE TITLE
[FEATURE]: Apply an order to multiple ships at once

### ISSUE THREAD

**Issue by kevinbroening** [Misunderstood-Wookiee/Mules-and-Warehosues-Extended#158]
Not sure if this is even possible, but I would love to be able to give the exact same orders to multiple ships at the same time.

I'm at the point in the game where I'm building batches of ships with my shipyard, and would love to be able to give orders to my supply mules (#2) so I can skip the monotony.

Sometimes I'm building 10, sometimes 50 large freighters and would love to apply the same supply mule order, of sending energy cells from my one station to my factory (one way freight) with only having to go through the menu once.

Not sure if this is possible, but I'd love to see it.

**Comment by bhayden53** [comment]
That's what mimic is for. Assign the order you want to a ship, then select the other ships, right-click the ship you want to mimic, and select "mimic for commander".

**Comment by kevinbroening** [comment]
I was not aware of this. Thank you for that tip.
