### ISSUE TITLE
[Potential Bug]: SupplyMule thinks my Barbarossa can transport only liquids and solids?

### ISSUE THREAD

**Issue by thijs** [Misunderstood-Wookiee/Mules-and-Warehosues-Extended#159]
When I setup my Barbarossa to be a SupplyMule it starts looking for wares with the list filled with only liquids and solids (methane, ore, etc). That seems like a bug?

**To Reproduce**
Steps to reproduce the behaviour:
1. Get a Barbarossa
2. Set it up as a SupplyMule
3. See error?!

**Expected Behaviour**
I expect a Barbarossa to trade container wares as that is what it can transport...

**Version Info:**
 - X4 Foundations : v5.10 [477240]
 - Mules Extended Mod : 6.42
 - I downloaded the mod from: Workshop

**Comment by bhayden53** [comment]
What it's doing is simply going through all of it's logic loops and looking for trades. What you're seeing is simply the last loop it tried. The wares are set by the valid trade offers it finds, so in this case, the last set of valid trade offers that the ship was offered were for solids and liquids.

By "valid" here I simply mean, stations offering purchases/sales. This ship can't queue up an order for something it can't carry, so it's harmless.

The ultimate issue here is that the ship is not finding any valid trade offers, so what you see in the end looks funny, but everything is working as intended.

**Comment by thijs** [comment]
Ah, okay, that makes sense. Maybe it should clear the list if nothing can be traded.

And I agree, it's weird that no trades are being found. Although I had just changed the trade blacklist, so maybe I made a mistake there...
