### ISSUE TITLE
[QUESTION]: The mod just does not turn on in the game. Downloaded from the nexus

### ISSUE THREAD

**Issue by VladossX** [Misunderstood-Wookiee/Mules-and-Warehosues-Extended#166]
When I turn it on in the addons menu and restart the game it stays off

**Comment by clc333** [comment]
I have the same issue but don't see anything regarding the fix here. Please advise. Thank you.

**Comment by VladossX** [comment]
> I have the same issue but don't see anything regarding the fix here. Please advise. Thank you.

In the game in the add-ons menu, you must disable the top item.
I do not remember his name but related to the workshop,after this item mod turned on
