### ISSUE TITLE
more options for travel mule

### ISSUE THREAD

**Issue by bhayden53** [Misunderstood-Wookiee/Mules-and-Warehosues-Extended#17]
travel mule sometimes seems like it's broken when really it's just kind of strict about when it will allow a trade to happen. Some of this could be exposed to the user to improve user experience.

**Comment by Misunderstood-Wookiee** [comment]
Need more info.
I did read about how it is a setting under and it won't trade
what kind of adjustment would you suggest be done.

**Comment by bhayden53** [comment]
Well there are two values that determine whether a trade will happen:
1) the profit of the trade. It does use the sell order price on your warehouse, and this seems to be a fairly big reason why the mule will appear stuck. The sell orders on the warehouses I've been testing were being set pretty high by the managers.
2) The percentage of the ship's cargo hold that the trade will take up. This has to be greater than the ships max cargo divided by 1.25.

Since travel mule has almost no options, I was thinking of exposing both of those values to the user as sliders. For 1), the slider would be the multiplier to apply to the warehouse sell offer, a value from 0 to 100 for instance. 0 means just sell everything regardless of price, 100 obeys the station managers orders. For 2, a simple slider that's say 25 to 100 for the percentage of the cargo hold that must be full for a trade to be valid.

**Comment by bhayden53** [comment]
Also keep in mind, for 1), even if the value is 0, the buying partner's price will be accounted for, so it'll still be looking for the best profit station to sell the wares to.

**Comment by bhayden53** [comment]
I could implement this in less than an hour, I think. But my test save is all screwed up and I need some time to get a new save going, and I'll be working all day.

**Comment by Misunderstood-Wookiee** [comment]
Just thinking on what may make the Mule look complicated to the user.
Sliders or a tick box, for Respect Station, Offers & Fill Cargo Hold
We would then change the routine so that by default it will sell regardless of price unless "respect Sation Offers = true

**Comment by Misunderstood-Wookiee** [comment]
> Also keep in mind, for 1), even if the value is 0, the buying partner's price will be accounted for, so it'll still be looking for the best profit station to sell the wares to.

Just thinking on what may make the Mule look complicated to the user.
Sliders or a tick box, for Respect Station, Offers & Fill Cargo Hold
We would then change the routine so that by default it will sell regardless of price unless "respect Sation Offers = true

**Comment by bhayden53** [comment]
I guess I was thinking of what I would want, and I like having granular control :)

If you think it should just be check boxes that's fine too.

**Comment by Misunderstood-Wookiee** [comment]
I am just thinking of what would look hard for the user. 
end of the day we have to explain to them how to use so the mule does what they want lol

I don't care either way slider or check box.

**Comment by Misunderstood-Wookiee** [comment]
> I guess I was thinking of what I would want, and I like having granular control :)
> 
> If you think it should just be check boxes that's fine too.

I am just thinking of what would look hard for the user.
end of the day we have to explain to them how to use so the mule does what they want lol

I don't care either way slider or check box.

**Comment by Misunderstood-Wookiee** [comment]
Untested but added as of https://github.com/Misunderstood-Wookiee/Mules-and-Warehosues-Extended/commit/fa4854e48b71d1de72f27850db7ad5b210dca7cf

New Options added to Travel Mule UI

- Profit Override

- Fill Cargo Hold %

`Param> minCargoUsed
Param> profitMargin`

Line 337 adjusted to make use of $profiMargin
Line 346 adjusted to make use of $minCargoUsed
