### ISSUE TITLE
[Beta Feedback]: Can not use mimic command on Mule fleet in 7.10 Beta 4

### ISSUE THREAD

**Issue by qwer11121-coder** [Misunderstood-Wookiee/Mules-and-Warehosues-Extended#174]
>Make sure you are indeed using Public Beta game patch prior to posting feedback & the public beta branch of this project's correctly installed and enabled!

### I have been testing the public beta patch and have this to say:**
I setup a fleet with 10 Barbarossa, and setup Ware Distribution Mule as default behaver for fleet leader.  Only fleet leader executed the command, all fleet members are in red error and shows "Can not assist fleet leader"

### IF APPLICABLE FILL OUT THE FOLLOWING
1. Select 10 Barbarossa and setup a fleet, use fleet command "Mimic"
2. For fleet leader, set default behaver to "M3 - Distribution Mule"
3. Uncheck "Assign to station"
4. Select a trade station as source
5. Select another trade station as target
6. Click OK to save
7. Only fleet leader start trade, all members are error.

**Expected Behaviour**
The default behaver should be copied to all fleet members 

**Screenshots**
![X4  Foundations Screenshot 2024 07 29 - 21 35 38 41](https://github.com/user-attachments/assets/9a9161f5-58e4-4a6c-bbc8-ff42dfe30338)

**Comment by Vectorial1024** [comment]
Why would a non-contributor suddenly be able to assign people?

---

Still, the 7.10 changelog mentioned something about bugfixing the Mimic command, so I expect the patch files need to be updated to match the new file content. Nothing too serious I guess.

**Comment by bhayden53** [comment]
Github has auto-assigned issues to us for a long time.

I'm not really playing X4 at all and not really all that interested in patching Mules at the moment.

**Comment by TheGreatGooglyMoogly** [comment]
It can be fixed by changing line 3 in order.assist.xml to something like...
<add sel="//do_if[@value='(@$orderdef and $createdefaultorder?) or not $order.requiredskill or (this.combinedskill ge $order.requiredskill)']">

**Comment by Misunderstood-Wookiee** [comment]
Merged, and will push a update out for this.
