### ISSUE TITLE
Travel Mule serious lagg if no Trades found

### ISSUE THREAD

**Issue by SM-Tiger** [Misunderstood-Wookiee/Mules-and-Warehosues-Extended#19]
Well i just tried out the Travel Mule.
If the station has no suitable Trades Game will start terribly lagging every 1 s.

Possible fix: Changing wait command at the end of script
`<wait exact="1000ms" /> ==> <wait min="10000ms" max="60000ms" />`

**Comment by bhayden53** [comment]
The update coming soon will have new config options in travel mule so that it won't hang as often. Longer waits won't make it today unfortunately.

**Comment by bhayden53** [comment]
hmm so I don't really get any lag if I intentionally set it up so that no trades are valid and it hangs forever. Not sure where the fix would be actually.

**Comment by SM-Tiger** [comment]
Can only tell you the second i activated them lagg started.
And as soon as i dismissed all those, that were searching for Trade and only left those, that already had one the lagg stopped.

When i started Modding on X Rebirth i learned, that you do that wait min/max command because it will be much less lagg. The Game itself will decide when it has ressources free to do the command, instead of forcing to command to execute at the exact time.

(I had 15 Travel Mules set up while in Game Pause. They probably have been doing the Search for Trade at the exact same ms. Maybe that being a reason for that extreme lagg :-/)

**Comment by Misunderstood-Wookiee** [comment]
> Can only tell you the second i activated them lagg started.
> And as soon as i dismissed all those, that were searching for Trade and only left those, that already had one the lagg stopped.
> 
> When i started Modding on X Rebirth i learned, that you do that wait min/max command because it will be much less lagg. The Game itself will decide when it has ressources free to do the command, instead of forcing to command to execute at the exact time.
> 
> (I had 15 Travel Mules set up while in Game Pause. They probably have been doing the Search for Trade at the exact same ms. Maybe that being a reason for that extreme lagg :-/)

This was known at least by me, not the lagg but the wait timers and was suggest I had just forgotten to make a ticket for this..  Adding a ticket now and trust me this is a thing I intended to fix asap.  

Our priority until now and for hopefully not too much longer has been re-writing the aspects of the mules into less error-prone routines and making them functionally stable. along with pushing any simple yet effective ideas that came up while refactoring.  Once we believe the mules are sorted to a respectful quality standard I fully intend to overhaul all wait timers. 

In meantime I am and I think I speak for us both, are happy to compare and PR merge any requests which help alleviate such a task from our hands in future.

**Comment by bhayden53** [comment]
We will get the wait timers in the mod moved over to min max format, thanks alot for the feedback.

**Comment by Misunderstood-Wookiee** [comment]
A ticket has been created for #21

**Comment by Misunderstood-Wookiee** [comment]
Closing for now.. but will leave open in-case issue should arise in future.
Hoping the latest build helps alleviate this issue. 

Improved timers as of: https://github.com/Misunderstood-Wookiee/Mules-and-Warehosues-Extended/tree/Release_v5.1.7
