### ISSUE TITLE
Lower skill requirements of Pilots

### ISSUE THREAD

**Issue by Misunderstood-Wookiee** [Misunderstood-Wookiee/Mules-and-Warehosues-Extended#2]
For better travel range per skill level.

**Comment by Misunderstood-Wookiee** [comment]
This was suggested by DeadAir unsure why.. exactly it is needed for our needs.

**Comment by bhayden53** [comment]
it seems like only supply mule has any dependence on skill. It's in the params section for maxDist if you want to look.

**Comment by Misunderstood-Wookiee** [comment]
Yea, deadair suggested lowering the required skill for it to be most effective at the job I believe, he reckons they all should be using a skill multiplier but I don't think it's a critical issue something we can look at and assess after the general people using the mod report that it's functionality is stable for them and will see what they all say after it just works as intended.

**Comment by Misunderstood-Wookiee** [comment]
Decided this was not needed, not after the refactor.
