### ISSUE TITLE
Optimise Wait-Timers to use Min/Max

### ISSUE THREAD

**Issue by Misunderstood-Wookiee** [Misunderstood-Wookiee/Mules-and-Warehosues-Extended#21]
Re-write all applicable static wait-timers into new dynamic min/max timers that do not bog down the script proceeding and/or hold up the games engine any longer than necessary. 

Currently, most of the wait timers are static in _milliseconds_  this simply will not do, there is no need for routines to refresh as early as they do in some cases and no need to keep refreshing when there is nothing to update for.  

So the current plan is to re-write the timer logic throughout all the scripts to use a dynamic _min_ wait time and _max_ wait time using the more robust method for optimisation reasons and code efficiency.

**Comment by bhayden53** [comment]
I changed them to min/max here b046a9f9f82bf4c1161cb936217d962e1eb0ce84 but did not change their overall values. Most of them are min="50ms" max="150ms". when the previous value was "100ms". Feel free to up them a bit,

**Comment by Misunderstood-Wookiee** [comment]
Completed as of https://github.com/Misunderstood-Wookiee/Mules-and-Warehosues-Extended/tree/Release_v5.1.7
