### ISSUE TITLE
supply mule not respecting user dock orders

### ISSUE THREAD

**Issue by bhayden53** [Misunderstood-Wookiee/Mules-and-Warehosues-Extended#23]
normally when a ship is doing some script you can give it a dock and wait order and it will obey that. The supply mule always seems to put it's own orders at the top. Not sure how to fix yet, just needs investigated.

**Comment by Galaxy-Spam** [comment]
Do you have any more information? For me the supply mule currently has the same behavior as the vanilla trader regarding dock & wait.
If there are others order in queue it will proceed with those, if there are none, it will wait.

**Comment by bhayden53** [comment]
I guess what I was looking for was a way to understand why for some orders, if I give a fly to order, it happens immediately, but for others, it waits. I will have to go back and find specific examples.
