### ISSUE TITLE
Mules Return Null Wares

### ISSUE THREAD

**Issue by Misunderstood-Wookiee** [Misunderstood-Wookiee/Mules-and-Warehosues-Extended#3]
Mules searching for trades return NULL wares.
Causes infinite trade search bug as reported on workshop and nexus.

**Comment by bhayden53** [comment]
fixed in https://github.com/Misunderstood-Wookiee/Mules-and-Warehosues-Extended/commit/4f8afb41daf56b4448b783df4505006e624af7d7
