### ISSUE TITLE
don't allow trades between the same station on supply mule

### ISSUE THREAD

**Issue by bhayden53** [Misunderstood-Wookiee/Mules-and-Warehosues-Extended#38]
if the prices are inverted such that it looks like buying and immediately selling to the same station will bring a profit, the supply mule can get stuck doing that in a loop. Should be a very simple check to make sure the owner stations of the trades are different

**Comment by Galaxy-Spam** [comment]
fixed in b9b224a792b25bd0047fa024472313c5fce1acca
