### ISSUE TITLE
Supply mules don't copy max jumps.

### ISSUE THREAD

**Issue by art4711** [Misunderstood-Wookiee/Mules-and-Warehosues-Extended#40]
When copying orders by assigning to another supply mule max jumps is not copied. All other params are copied verbatim, maxDist is explicitly set to `@this.ship.pilot.skill.piloting * 2`.

**Comment by bhayden53** [comment]
Yes, this is because the max distance should be dependent on the new pilot's piloting skill, not the pilot who is being used to copy the order from.

**Comment by bhayden53** [comment]
Sorry pressed the wrong comment button.

I see what you're saying, I'll come up with a fix.
