### ISSUE TITLE
supply mule performance issue when source station runs out of money

### ISSUE THREAD

**Issue by Galaxy-Spam** [Misunderstood-Wookiee/Mules-and-Warehosues-Extended#46]
When a station runs out of money and subordinate supply mule wants to make a supply run at a NPC station the script runs into and endless loop and basically crashes performance.
Steps to reproduce:
1) Setup a new production station without any budget (or let it run out)
2) Make sure you dont have any player station producing the required goods
3) Assign a supply mule to the station using the subordinate feature (checkbox: Assign Ship To Station)
4) Watch your fps drop.

In the error log you can see the failsave from egosoft kicking in:
```[Scripts] 175006.05 *** aicontext<order.trade.perform,0x3aa02>: 175006.054 'Supply Mule (Claytronics Factory Alpha)'(job: '') TRADE RUN FAILED! Error: ERR_NO_CARGO_SPACE
[General] 175006.05 ======================================
[=ERROR=] 175006.05 Prevented account 0x110 from going negative, see callstack [ Michael ]
[General] 175006.05 ======================================
```

The debug log from the mule:

```
ScriptStart
found subordinates: 0
 Setting subordinates used up: 0 Seconds
 Selling leftover cargo used up: 0 Seconds
Define Wares
dedicated serve: 1
sourceStation: 0x3aa2c
----- Source Station set to Claytronics Factory Alpha. Entering Source Station owned by Player block 
----- player supply to station build storage
----- station build needs
stationBuildNeeds count: 0
station build storage needs:
----- player owned supply offers
playerSupplyOffers count: 0
player Supply Offers:
----- ai to station build storage
----- station build needs
stationBuildNeeds count: 0
station build storage needs:
----- ai supply offers
aiSupplyOffers count: 7
ai Supply Offers:
    FRF Quantum Tube Factory I Quantum Tubes 2272 -0.487333 0 0.6497
    FRF Microchip Factory II Microchips 2425 -0.884545 0 0.846422
    FRF Quantum Tube Factory I Quantum Tubes 5762 -0.833733 0 0.821149
    TEL Microchip Factory I Microchips 4874 -0.95028 0 0.841506
    FRF Quantum Tube Factory I Quantum Tubes 2374 -0.557467 0 0.676739
    FRF Microchip Factory I Microchips 7847 -1 0 0.482981
    FRF Antimatter Cell Factory I Antimatter Cells 52492 -1 0 0.989276
----- player to station production goods
----- station product needs
stationProductNeeds count: 3
station product storage needs:
    Claytronics Factory Alpha Antimatter Cells 0 0.99925 7046 0
    Claytronics Factory Alpha Microchips 0 0.505775 7534 0
    Claytronics Factory Alpha Quantum Tubes 0 1 7462 0
----- player supply offers
playerSupplyOffers count: 0
player Supply Offers:
----- anyone to station production goods
----- station product needs
stationProductNeeds count: 3
station product storage needs:
    Claytronics Factory Alpha Antimatter Cells 0 0.99925 7046 0
    Claytronics Factory Alpha Microchips 0 0.505775 7534 0
    Claytronics Factory Alpha Quantum Tubes 0 1 7462 0
----- ai supply offers
aiSupplyOffers count: 7
ai Supply Offers:
    FRF Quantum Tube Factory I Quantum Tubes 2272 -0.487333 0 0.6497
    FRF Microchip Factory II Microchips 2425 -0.884545 0 0.846422
    FRF Quantum Tube Factory I Quantum Tubes 5762 -0.833733 0 0.821149
    TEL Microchip Factory I Microchips 4874 -0.95028 0 0.841506
    FRF Quantum Tube Factory I Quantum Tubes 2374 -0.557467 0 0.676739
    FRF Microchip Factory I Microchips 7847 -1 0 0.482981
    FRF Antimatter Cell Factory I Antimatter Cells 52492 -1 0 0.989276
ship capacity: 7500
Occupied Cargo: 0
----- trade offer comparisons
Antimatter Cells target desired amount 7046 supply amount: 52492 ship can hold: 416 amount will be: 416 need unitprice: 28194 supp unitprice: 12100 player buy modifier: 0 profit: 6695104
Microchips target desired amount 7534 supply amount: 2425 ship can hold: 340 amount will be: 340 need unitprice: 101982 supp unitprice: 82151 player buy modifier: 0 profit: 6742540
Microchips target desired amount 7534 supply amount: 4874 ship can hold: 340 amount will be: 340 need unitprice: 101982 supp unitprice: 81211 player buy modifier: 0 profit: 7062140
Microchips target desired amount 7534 supply amount: 7847 ship can hold: 340 amount will be: 340 need unitprice: 101982 supp unitprice: 80500 player buy modifier: 0 profit: 7303880
Quantum Tubes target desired amount 7462 supply amount: 2272 ship can hold: 340 amount will be: 340 need unitprice: 37500 supp unitprice: 26345 player buy modifier: 0 profit: 3792700
Quantum Tubes target desired amount 7462 supply amount: 5762 ship can hold: 340 amount will be: 340 need unitprice: 37500 supp unitprice: 23747 player buy modifier: 0 profit: 4676020
Quantum Tubes target desired amount 7462 supply amount: 2374 ship can hold: 340 amount will be: 340 need unitprice: 37500 supp unitprice: 25819 player buy modifier: 0 profit: 3971540
buying 340 Microchips from FRF Microchip Factory I at 805 Cr to sell to Claytronics Factory Alpha at 1,019 Cr for a profit of 73,038 Cr
Occupied Cargo: 7480
Cargo Full, No More Trades
******* went to end
```

The fix would require the mule to take the stations balance into account if it is a subordinate and trading with NPC stations.
I will try to provide a patch later today.
For now the workaround would be to make sure the station has enough funds.

**Comment by bhayden53** [comment]
At the moment I don't know how to check that the station can afford the trade. There are a number of locations in the code that will all need the same fix (supply mule is a monstrous copy and paste / repeated code job, because I am a python programmer and I don't like to use labels for flow control).

Probably the main reason I've never seen this is that I use this mod for auto credit transfers:
https://steamcommunity.com/sharedfiles/filedetails/?id=1927314272&searchtext=transfer

**Comment by Galaxy-Spam** [comment]
Yeah, it's quite a bit of copy and paste. 
I still checking how to implement the check for station account by digging though thier orginial trade code. In the worst case, i might need to implement a try/catch statement, however i want to avoid at all cost it if possible.
(Maybe consider <run_script> as a function style replacement? It should not affect performance as fas as  i know from egosoft postings? Might serve you better, then labels (which i dislike very much as well since it makes debugging very hard).

**Comment by bhayden53** [comment]
there was no check in the original code. In fact I don't think there's any checks in any of the trade scripts that I've used as reference.

**Comment by bhayden53** [comment]
Mewosmith (on the x4 modding discord) told me not to use run script as a function, he said it would cause bad performance issues.

**Comment by bhayden53** [comment]
If you're able to figure out one of them, just do a PR with a single example and I'll apply it everywhere it's needed in the script. Don't worry about patching the whole monstrosity.

**Comment by Galaxy-Spam** [comment]
Alright, will do. It's probably hidden somewhere in the internal functions (like find_sell_offer). Thanks for the info.

**Comment by bhayden53** [comment]
It might be something simple like using tradeoffer.amount somewhere, instead of tradeoffer.desiredamount, when trading with the AI. i.e. in this block:
`<set_value name="$tradeAmount" exact="[$targetDesiredAmount,$supplyAmount,$cargoHauled].min" />`

We may need another variable that's:
`<set_value name="$tradeAmount" exact="[$targetDesiredAmount,$supplyAmount,$cargoHauled,$targetAmount].min" />`

So in the place where $targetDesiredAmount is defined, we'd define $targetAmount too. Then if it's small due to budget constraints, it'll be the value that's picked here. 

It looks like you're in the block that starts on line 2242, so if you still have the save with the issue, you could try implementing something like what I said and see if that works.

note: desiredamount on the source station order is basically the amount of allocated storage that's not filled. On the target station, I believe it's the total amount they have in storage. amount should be the amount that the trader specified in the <find_sell_offer> can afford on that trade, but I haven't tested that value extensively to make sure.

**Comment by Galaxy-Spam** [comment]
Your guess was right, buyoffer.amount stores the actual possible amount. I'm not, sure, but it seems the $targetDesiredAmount could be removed from calculation without any issues, since the $targetAmount should always be lower.

**Comment by bhayden53** [comment]
You would think, but we'd have to make sure egosoft's object is actually working that way....

**Comment by Galaxy-Spam** [comment]
Haha, true :D

**Comment by Galaxy-Spam** [comment]
So, i just had a very similar error again when buying buildstorage from an NPC.
What seems to happen is, that the station makes a trade offer for build storage goods using it's build storage account for financing. 
However, when the trader then places the order, it is still assigned as a normal trader, meaning it will use the normal station account for funds! 
If the account is empty, then we are in a loop. 
But even if the account has money, it is drained for construction (which is not the intended way).
Therefore, the trading ship must be assigned to the build storage traders before placing the order.
I will test this tomorrow and will add another PR.

Also, the prober way & safer way to limit the buy amount is using <clamp_trade_amount> instead of manually check the cargo hold size, since clamping takes into accout stuff like reservations etc. This should not be a problem in our case, but it also doesn't hurt and makes to code cleaner.

**Comment by bhayden53** [comment]
I'm pretty sure that amount and desiredamount also take reservations into account. I've never seen a supply mule buy more than the target wants, and I frequently have 10 supply mules set up just for build storage. Also, using clamp_trade_amount will not stop us from having to check the cargo hold, because the clamped amount could still be less than the minimum that we want to allow for a trade to be considered valid.

I'm not sold on assigning mules directly to build storage. I don't even know if it's possible and I'm not sure if that's even how vanilla station auto traders work. It's not something I'm really all that interested in doing, moving commanders/subordinates around alot in the code. Seems bound to cause headaches. Would probably require a global to remember the original commander, because you'd lose the knowledge of what the player set after the first time through the order. If the build storage disappears I'm not sure what happens. Then you'd have to set it back to the original station, and if the new order is for build storage again, you'd have to flip it back to build storage. There's a performance cost to that. And this is if you can even assign ships directly to build storage. So I'm seeing at least 4-6+ hours of work there, and that's just not that high on my priority list.

**Comment by bhayden53** [comment]
If you come up with a clean solution, I'll certainly test it and see what I think. Even testing one change is typically a whole evening's worth of work.

**Comment by Galaxy-Spam** [comment]
So, im still trying to figure out a better solution.
But with egosofts current implementation i think it would require a huge workaround, since egosoft does it also "wrong" (only buys building supplies if the station has money in it's production account and also uses it's production account for buying the resources.), but at least just discards the whole trade offer then.

Currently the following is happening

- We look for buyoffers at our buildstorage
- It gives a list with wares it needs and the amount it can afford.
- We then look for sell offer and find a match
- We restrict the amount based on the amount the buildstorage can afford (because that what the buyoffer is based on)
- We try to issue a buy order but fail, because our ship want's to take money from the stations account, but not the build storage account

Egosoft "solved" this by performing an additonal check:
```
<clamp_trade_amount trade="$selloffer" amount="$selloffer.amount" buyer="this.assignedcontrolled" seller="$selloffer.seller" result="$amount" />
```
Where the selloffer is reduced to actual money the ship (based on the stations money) can afford.
So currently we should use clamp_trade_amount in order to reduce the affordable amout based on the stations finances.

**Comment by bhayden53** [comment]
switching the whole script to using clamp_trade_amount will be a several hour investment, and will probably end up spread over multiple days of work and testing. I'll get to it but I want to knock out some easier stuff first.

**Comment by Galaxy-Spam** [comment]
While it would be the "proper" way to change everything using clamp_trade_amount, i dont think it's needed for fixing the issues at hand (rather it would be a part of refactoring the code). 

The changes are only required when assigened to owner source stations and buying from anyone ( 6 cases ).
In the cases of selling to your own source station, we dont require clamp_trade_amount, since the offer amount should have taken care of this (2 cases).

I would still implement the check in these cases for consistency, if this is not a performance issue.
I could implement the changes to all 6 cases, if it would help you. But i assume for now that you are refactoring the code anyway, and therefore this would not help?

**Comment by bhayden53** [comment]
right now I'm working on some lingering issues in other mule scripts, so if you want to contribute, I probably won't be in the supply mule script in the coming few hours.

**Comment by bhayden53** [comment]
Did you test clamp_trade_amount to see that it takes funding into account? It only talks about storage in all of the docstrings and I'm just wondering if it's working the way we think.

I've been cleaning up some other issues, one of which involves checking the reservations, so I've been poking around in this type of area.

**Comment by bhayden53** [comment]
I did some further testing last night and it does appear that clamp_trade_amount takes funding into account; just needed to verify that one for myself. However, when queuing up multiple trades, the sum of the buy offers seems to be allowed to go over the account balance, which seems to indicate that it doesn't take the cost of your reservations into account.

I spend so little time at low balance that I'm not going to mess with that contingency.

**Comment by Galaxy-Spam** [comment]
Alright. I will contribute as much as possible to at least ensure that we avoid the endless loops.
I dont mind if the trade fails from time to time, but if the fps drop below 10, it is an issue for me. 
Most people probably won't notice the reason and just deactivate the mod. And the mod is a real good addition to the current trade system.
