### ISSUE TITLE
Mules Ignore Global Blacklists

### ISSUE THREAD

**Issue by Misunderstood-Wookiee** [Misunderstood-Wookiee/Mules-and-Warehosues-Extended#5]
Figure out why mules will not use global blacklists for trade and travel.

**Comment by bhayden53** [comment]
example from tatertrader for filtering blacklisted offers:
```
<find_sell_offer tradepartner="this.ship" space="$buyspaces.{$sector}" result="$sellers" multiple="true" wares="$stationbuyoffer.ware">
    <match_seller>
        <match_relation_to object="this.ship" relation="enemy" comparison="not"/>
        <match tradesknownto="this.owner"/>
        <match_use_blacklist group="$blacklistgroup" type="blacklisttype.objectactivity" object="this.ship"/>
    </match_seller>
</find_sell_offer>
```

So we'll need to find the right filters to use, and then go through and apply them to every find_sell_offer and every find_buy_offer

**Comment by bhayden53** [comment]
I think we can just pull out that match_seller block and apply it to every find_sell_offer. Then make a similar match_buyer for all find_buy_offer

**Comment by bhayden53** [comment]
Working on this now, hoping it's a simple fix then I can move on to the other stuff.

**Comment by bhayden53** [comment]
All mules should be adhering to all blacklists, as far as I can tell.
