### ISSUE TITLE
Tighten up and/or review buy/sell offer search spaces (esp in supply mule)

### ISSUE THREAD

**Issue by bhayden53** [Misunderstood-Wookiee/Mules-and-Warehosues-Extended#58]
There are a number of paths that could be taken here. One that seems popular is too build a list of not-blacklisted sectors and loop over the sectors, finding offers in each one. Each call to find_buy_offers is therefore small but now you're doing a bunch of calls. 

Don't want to do this one until after the supply mule refactor in https://github.com/Misunderstood-Wookiee/Mules-and-Warehouses-Extended/issues/57 progresses.

**Comment by Misunderstood-Wookiee** [comment]
Good idea,

**Comment by Galaxy-Spam** [comment]
What is the aim? Performance gain?
If so, how much mules cause a performance impact?
If it's 10k or more, one could cache buyoffers in a global variable (but i would guess egosoft caches those by default).

**Comment by bhayden53** [comment]
This issue came out of the discussion about large searches for trades causing hiccups in the frame. A couple of the buy from ai trades are probably too expansive, or at least warrant a review.

**Comment by Galaxy-Spam** [comment]
From what i have seen, there are only frame hickups, if we search the whole universe (eg. jump distance 30, including ai) for all wares required by all stations in a sector and dont find anything. Not sure how to mitigate it best. But i doubt thats related to the sell/buyoffer search. But rather the loop of comparing buy/sell offers.
I can literally call
```
<find_buy_offer space="player.galaxy" tradepartner="this.ship" result="$needs" multiple="true" />
```
with no performance loss. 
We could insert a wait in the loop to force the script to idle, but i'm not sure thats the best way to handle it.

**Comment by bhayden53** [comment]
Perhaps we can close this ticket, I think this review is a natural part of the supply mule refactor that Galaxy-Spam is doing anyway. I'll think about it a little more and probably close it tonight.

**Comment by bhayden53** [comment]
Closing this ticket. in the long run, it might be better to refactor yet again to do very small, focused find_sell_offer's for every buy offer. This is how it's handled in vanilla and in tater, and may provide some performance benefit. This also allows for something like the scantickrate in tater to be tuned to throttle the scripts and keep them from being too much of a drag on performance as well. But that's beyond the intended scope of this issue. With the supply mule refactor, I'm relatively happy with where the mules are today.
