### ISSUE TITLE
Station Mules trading for other stations

### ISSUE THREAD

**Issue by TCESylver** [Misunderstood-Wookiee/Mules-and-Warehosues-Extended#63]
So I have a bunch of stations, ore refinery, methane refinery etc. I assigned a station mule to each of them to trade to a warehouse. I ticked the assign to station , two way trade, and make target a warehouse boxes. It started out working well, but now i see different traders trading with stations they are not assigned to and others just standing still while there is enough ware to trade.

**Comment by bhayden53** [comment]
station mules will work for other stations when the other stations have more urgent priorities than the home. This may be addressed with a "serve source only" param in the future.

**Comment by TCESylver** [comment]
Ah that explains it. I would love a serve source only param in the future!

**Comment by TCESylver** [comment]
One thing, I have a supply mule assigned to a player wharf on source only, yet it still takes stuff from other stations and takes it to a warehouse station. Not just supplying the wharf.

**Comment by bhayden53** [comment]
Yes we noticed a bug today with serve source only. The good news is, where it is in the code means that the home station does not need any wares for their immediate production. It happens once we start checking for trade wares. However, it's still annoying that the param doesn't work, sorry about that.

**Comment by bhayden53** [comment]
work will be attached to https://github.com/Misunderstood-Wookiee/Mules-and-Warehouses-Extended/issues/64 so closing this as duplicate.
