### ISSUE TITLE
Nexus release not working.... (without additional steps)

### ISSUE THREAD

**Issue by DoctorVanGogh** [Misunderstood-Wookiee/Mules-and-Warehosues-Extended#65]
This mod is published on Nexus. Presumably one should be able to download from there and use it. **That won't work** ;)

Downloading and "unpacking" the mod from nexus will _always_ show the mod as `off` in the main menu extensions screen _unless_ you **also** subscribe to the workshop item on steam.
![image](https://user-images.githubusercontent.com/324067/81510325-24d6b780-9311-11ea-905d-b257a0aaf00d.png)
![image](https://user-images.githubusercontent.com/324067/81510329-2c965c00-9311-11ea-9d8d-be109c5db74f.png)

But if you subscribe to the workshop item on steam you don't need a nexus download... and presumably if you distribute via nexus you don't want to force people into downloading via a _secondary_ channel ;)

## Fix:
Rename the mod folder from `ws_......` to `AnythingBut_ws_..`and change the `id` attribute inside `content.xml` the same (for any non steam release)
Extensions screen will correctly show the mod as a "non steam" mod and allow users to enable the mod.

![image](https://user-images.githubusercontent.com/324067/81510332-35872d80-9311-11ea-8912-f1cc82834d6c.png)

### Additional issue:
The Nexus release doesn't have a "mod manager" download link.... Pretty please? :grin:

**Comment by Misunderstood-Wookiee** [comment]
Delete ws_ I have seen this before in many times it's when steam tries to update a mod  not gotten from workshop but placed in the extention folder what will happen is you wind up with a duplicate which will appear as a red mod and likely named the same as the original and you'll have a mod with the ws_ however not always the case sometime it just rename the same name mod to ws_ with the workshop ID it's quite an annoying thing and yes you'll have to disable update and sub I can fix this pretty easily by turning sync false to the Nexus mod upload in the content.xml this will load the mod not subscribed on first use I simply forgot about this and is was my oversight however the mod will still function despite its name.

I'll upload a fix today to prevent occuring again to fix yourself just open content.xml and change the ID to anything else or turn sync true to a false.

However this issue won't effect everyone and is a simple solution.


Nexus does have a mod manager, however,  it's called Vortex but I don't trust it installing mods for this game as it's known to do so incorrectly for if people request it I can enable the manager download url again.

**To get the file just download the mod from Nexus from the files tab.**

**Comment by Misunderstood-Wookiee** [comment]
Resolved

**Comment by bhayden53** [comment]
fwiw I believe all of the issues with vortex for X4 have been fixed by the nexus team
