### ISSUE TITLE
supply mule needs split dlc ware updates

### ISSUE THREAD

**Issue by bhayden53** [Misunderstood-Wookiee/Mules-and-Warehosues-Extended#7]
there's a warelist hardcoded in the supply mule that needs updated with the new wares

**Comment by Misunderstood-Wookiee** [comment]
Easily done,  TaterTrader has the correct list I will look it up from that.

**Comment by Misunderstood-Wookiee** [comment]
I think this might still be an issue.

**Comment by bhayden53** [comment]
that wareList only gets used if certain checkboxes aren't checked.

**Comment by bhayden53** [comment]
hmm yeah I triggered the use of that wareList I don't see for instance chelt meat on there.

**Comment by bhayden53** [comment]
oh wait maybe I do, is it just "meat"?

**Comment by Misunderstood-Wookiee** [comment]
> oh wait maybe I do, is it just "meat"?


_Split Wares_
> ware_cheltmeat
> ware_scruffinfruit

**Comment by bhayden53** [comment]
I still think there's something weird here, when supply mule makes a warelist in the mod UI the split ones aren't there. I don't know where the warelist is coming from, I had assumed it was the hardcoded list in the mod, but maybe not.

**Comment by bhayden53** [comment]
So far in my re-write I'm not hardcoding any full list of wares in the game.
