### ISSUE TITLE
"ignore trade rules" param?

### ISSUE THREAD

**Issue by bhayden53** [Misunderstood-Wookiee/Mules-and-Warehosues-Extended#79]
XeonCore on steam wants to be able to stop the AI from trading at their warehouse, but have the supply mule and travel mules on that warehouse be unrestricted. I am hesitant to add another param but we do already have at least one problem in https://github.com/Misunderstood-Wookiee/Mules-and-Warehouses-Extended/issues/78.

**Comment by bhayden53** [comment]
@Galaxy-Spam @Misunderstood-Wookiee  thoughts?

**Comment by Misunderstood-Wookiee** [comment]
I'm pretty sure I'm already doing this with 3.2 trade bans on two of my stations.

I will confirm this evening using the vanilla trade ban I deny docking at them and any trade type for certain factions.

**Comment by bhayden53** [comment]
Ok, I didn't think there was a way to do this, because any trade rules that are setup to stop the AI from trading should also stop the mules from going out and making those trades as well. He wants to stop the AI from trading but have the mules be unrestricted. Let me know if you found a way to do that.

**Comment by Misunderstood-Wookiee** [comment]
Yeah, in this case, you don't want to use the older trade ban instead you want to use the trade bans introduced in 3.20 this allows you to choose if the ban applies to both the AI and you or not it's more flexible then saying okay no trade from this faction can happen.

**Stations can be told to use trade bans for individual wares like this -** 
https://i.imgur.com/hEAbine.png
You can also set a station to use any trade or blacklist global you created separately if needed, 
This means you can use a trade ban alongside a blacklist and it does not have to be the same global default,  FYI blacklist and trade ban will only be default applied if you tick any boxes

 **You may also choose to assign trade ban or blacklist rule  or remove a global default manually by going into the individual orders of a ship or station just not tick every box and it won't become the default rule.** 
https://i.imgur.com/FLJqPIg.gifv

Now for Trade Bans & Blacklist control, you can do something like this - 
https://i.imgur.com/wAXMjWV.gifv
Use in combination with Station per ware rules above + individual ship action settings as you can see in the example only if I have tick anything will it become a default action so I can choose to ban all factions on a case by case simply by telling the station or ship to obey that rule. 

Likewise if you were to combine that with Invert Rule I think you will find all cases of control for if AI can trade but own can't or own can and AI can't are resolved with vanilla so I don't think we need a param for this at all IMO.
