### ISSUE TITLE
[Potential Bug]: Loop order being deleted

### ISSUE THREAD

**Issue by z1ppeh** [Misunderstood-Wookiee/Mules-and-Warehosues-Extended#80]
>Please check for an existing issue before making a new report and comment in that report if one exists.

**Describe the Bug**
Orders stack up, then get deleted,  then stack again, then get deleted.  Some rediculous amount of times per second thus slashing FPS to a minimum until the mule / mules in question are unassigned.

**To Reproduce**
1.  HOP must have SC2 / SC2 must be blocked off. (this is currently the only thing I have found it to affect but I have not really tried to do it any other way).
2. Blacklist for ALL  HOP space for the mule  in question not to enter.  Does not matter what type of blacklist is in play, it must berely prevent all civs from enemy space with HOP as a faction selected.
3.  Supply  mule on limited gate  amount on 5 gates working from Argon Prime from a hull parts factory.
4. Factory in Black hole  sun wants hull parts and the best deal that the script will pickup as its chosen journey... 99 times out of 100 (dependong on galaxy ofc as it sometimes picks up something else... but then another mule just gets caught in the trap).
In  theory the supply mule should ignore the supplies to blackhole sun as the other route is a LOT further round if he is barred from going through SC2.

Instead he creates a route to black hole sun, the blacklists are acknowledged and he reroutes  the long way around, the mules script registers that the journey is too long, orders are deleted. start the script again.

It then  repeats the process some rediculous amounts of times (never stopping... and so quick because your damn algorithms are so  good)

**Expected Behaviour**

Not sure, I  expect  it to work? :)

**Version Info (please complete the following information):**
x4 3.2
Mules extended 6.1 and backwards.
Nexus.

**Screenshots**
None.  I will attempt to replicate this again shortly and provide evidence.

**Additional context**
Massively mod heavy but... in theory.. nothing else touches movements or blacklists and that is the only thing mules would touch.

**Comment by bhayden53** [comment]
> the mules script registers that the journey is too long

This is the thing I keep trying to explain to you is impossible. Once the AIScript makes the trade, the mule is in vanilla hands. Vanilla is cancelling all of the orders for some reason. Even if somehow mules did get control, we don't have any code that deletes orders. 

Can you turn on debug logging and send me the main X4 debug log when this happens? If you still have a save where it's occuring? 

This still sounds like a 100% vanilla bug to me, I'd be surprised if it has anything to do with our code at all.

**Comment by FormBurden** [comment]
@z1ppeh If it turns out to be a vanilla bug, I suggest reporting it on the forums. The devs are pretty good when people report bugs.

**Comment by z1ppeh** [comment]
No  longer an issue as it was a very particular blacklist issue that has now been fixed.
