### ISSUE TITLE
[Potential Bug]: L  mules with no drones attempting to trade with a station with no drones sit there and cause FPS loss.

### ISSUE THREAD

**Issue by z1ppeh** [Misunderstood-Wookiee/Mules-and-Warehosues-Extended#82]
>Please check for an existing issue before making a new report and comment in that report if one exists. Checked and no issues with teh words drone or drones in it

**Describe the Bug**
Having a travel / supply mule that does not have drones that attempts to trade with a station with no drones merely makes him sit there repeating his orders again and again and again.

**To Reproduce**
Any L/XL mule with no drones, going to buy wares from a player owned / AI owned station with no drones.

**Expected Behaviour**
Maybe a cancellation of the behaviour and a logbook entry or a help popup to highlight the issue with that particular ship?  On any decent computer this is barely noticable for the first 1-5 mules with this issue but then when multiple mules hit the same issue it can tank the fps down.  Once a mega trade empire is built and ships are assigned in multi batches it can make finding the specific ships a nuisance without logging.

**Version Info (please complete the following information):**
Everything is current version.  X4 3.2 and Mules 6.1
**Screenshots**

**Additional context**

**Comment by Galaxy-Spam** [comment]
Thanks for the report. I will try to reproduce it tomorrow.
I don't see why it should tank fps, thats a bit wierd (it should wait 3 mins before searching again).
For L/XL Ships, we could probably add a Message if your ship carries no drones and has not found a trade. 
Could you provide a list of Mule settings with the FPS drops?

**Comment by z1ppeh** [comment]
I think it  tanks because the order is cancelled where there are no drones available, the order is then created in replicate instantly.  One little guy in an infinite loop isn't  so  bad unless your running a potato.  You will  notice it the most if you add each mule slowly to a live game that hits this infinite loop and your fps will drop.

My travel mule was how I found it  but then when testing with a supply mule limited to sales to my own stations he will buy from the AI which is fine as they all have drones (but its much harder to find the little bugger when you don't know which station hes at) but when he attempts to setup the order to sell to the player station is when it goes wrong.

**Comment by Galaxy-Spam** [comment]
I was able to reproduce it.
```
[=ERROR=] 24587.78 aicontext<order.trade.perform,0x18c165f>: JZY-065 Sonra Vanguard 0x8d85b8 is a capital ship that is about to trade but has no cargolifters. attempting to recover.
```
Hopefully i can get a fix out today.

**Comment by Galaxy-Spam** [comment]
I did manage to fix the problem. Once this is merged, we should be fine for travel and supply mules. However, the same problem persists for station and distrib mule for now!

**Comment by Galaxy-Spam** [comment]
Im not sure about added messages. 
The main problem is the possible Message log spam.
Case: 
Players always supply thier stations with drones, but never the ships
There is currently nothing to Trade.
Result:
We can't really distingush the cases "no drones at all" and "nothing to trade"....
