### ISSUE TITLE
[Potential Bug]: I think I found a bug!

### ISSUE THREAD

**Issue by z1ppeh** [Misunderstood-Wookiee/Mules-and-Warehosues-Extended#83]
>Please check for an existing issue before making a new report and comment in that report if one exists.  Not sure if bug or feature...

**Describe the Bug**
Miner ships assigned as a travel mule are assigned wares that will never be able to carry on their cargo.  In this particular instance I am using travel mules to get rid of nividium from my PHQ after research is complete, but this would also apply to cases where someone builds a mining station

The workaround is to add the wares and lock them to user selected.

**To Reproduce**
Have a miner ship assigned as a travel mule without specific locked restrictions.  He will be auto assigned wares that will not fit his cargo.

**Expected Behaviour**
A ship should be checked for its cargo type prior to the wares being assigned

**Version Info (please complete the following information):**
All latest versions, x4 3.2, mules 6.1 git.

**Screenshots**

**Additional context**

**Comment by Galaxy-Spam** [comment]
Hmm, i just tried to reproduce this. 
For me, it does work just fine and the miner never tries to sell cargo it cannot carry.
Do you have a screenshot of your setting (ship + station) or maybe better a savegame?

**Comment by Galaxy-Spam** [comment]
On that note, we should probably clarifiy the user experience here (as well as performance).
Because the travel mule will list other wares in it's basket that it cannot sell, and will try to compare trade offers here. They do all fail, because the miner can't haul energycells etc. (cargo size 0) and (to my knowlege) are all ignored.
We should consider filtering out the wares before searching for trades here.

**Comment by bhayden53** [comment]
It lists the wares in the basket but when the trades are evaluated, we use an attribute that checks the container type to make sure the ship can carry the ware. 

Basically we never filter the list of needs that shows up in the UI by whether or not the ship can carry it. It's a "bug" in one sense, but it's harmless in the sense that the ship will never attempt to create a trade for something it can't carry in it's cargo type.
