### ISSUE TITLE
[FEATURE]: Have supply mules work as traders when idle

### ISSUE THREAD

**Issue by probablynotpotato** [Misunderstood-Wookiee/Mules-and-Warehosues-Extended#86]
**Is your feature request related to an existing problem or suggestion? (Please use issue URL'S if yes).**
Yes, it's a workaround to [idle mules creating extra CPU load spikes](https://github.com/Misunderstood-Wookiee/Mules-and-Warehouses-Extended/issues/85), by not letting them idle.
I'm posting this separately because it's not a complete solution, but would also be amazing for player infrastructure efficiency.

**Describe the solution you'd like:**
Supply mule that could work as trade mule when otherwise idle could be the "ultimate" mule, equivalent to a station trader but performing better in every aspect, capable of serving any number of stations in a single fleet.
The currectly two set of settings settings could coexist in one behavior. Priorities are pretty much like normal supply mule and if nothing to do, then proceed like a trade mule would.

1. Supply build storage
2. Supply production
3. Sell own wares from already defined home+maxjumps area using a maximum of X jumps

**Describe alternatives you've considered:**
The alternative to this are vanilla station traders which are rather awful.
Having both trader and supplier fleets is of course possible, but there's no interoperability which lets many of them go idle depending on the economy.

**Additional Context (if any)**
JP mods already do something similar, they have a simple "when idle do X" ruleset that's copied between available behaviors. They return to work eventually when there is something to do.
![image](https://user-images.githubusercontent.com/11718005/85144064-ee168a00-b24a-11ea-901f-dcf117fa5727.png)

**Comment by Misunderstood-Wookiee** [comment]
I do like this..
question is time, I really wanna track down this frame dip problem before I drift away into making a mule param I also wanna re-do the param list so it is easier to use.

**Comment by bhayden53** [comment]
I'm not really working on mules much right now. There's probably 4 or 5 things on mules I would need to do before I'd even think about doing it. And even then, I'm not really a fan of the idea.
