### ISSUE TITLE
[Potential Bug]: I think I found a bug!

### ISSUE THREAD

**Issue by probablynotpotato** [Misunderstood-Wookiee/Mules-and-Warehosues-Extended#87]
**Describe the Bug**
Mule getting teleported very far away, somehow.
This may or may not actually be related to mules, but this bug is supposed to have been fixed a long time ago, and so far 3 out of 3 times it happened to a mule.

**To Reproduce**
Steps to reproduce the behaviour:
No idea, I just keep finding it that way.

**Expected Behaviour**
No ship should teleport way outside the standard sector borders.

**Version Info (please complete the following information):**
 - X4 Foundations : 3.2
 - Mules Extended Mod : CPU hotfix I got some days ago (but it happened on a stable version too)
 - I downloaded the mod from: Discord

**Screenshots**
![image](https://user-images.githubusercontent.com/11718005/85236386-dd6a3d80-b41d-11ea-8a11-78bf5260d3a6.png)

**Comment by bhayden53** [comment]
This always used to happen to me with TaterTraders. I think it's some kind of vanilla bug. Not sure there's anything we can do about it.

**Comment by Galaxy-Spam** [comment]
Sound like a vanilla problem, since we dont move ships at all, we just issue vanilla orders.
Best to report it in egosofts forum. Close?

**Comment by Misunderstood-Wookiee** [comment]
I agree with the others, non of the mule scripts mess with ship movement, we don't teleport anything around or make any kind of custom adjustments too ship speed or anything so this entirely vanilla I guess some types of orders bring out the worst case scenarios for ship movement. If I remember correctly there is always a chance this will happen when going through gates at speed.
