### ISSUE TITLE
Travel Mule loop : buying and selling to the same station

### ISSUE THREAD

**Issue by BinaryJourney** [Misunderstood-Wookiee/Mules-and-Warehosues-Extended#93]
I went and took a look at previous treads but didnt see this issue anywhere, so I don't know if its a bug or if I misunderstood something but I have been stuck with it for quite some time and can't find a solution to it.

**Here is the context :** I got a Warehouse / Trading Station with, let's say, only Refined Metal. I fill up the warehouse only with products which where made from my factories (Refined Metal here) and then I want a Travel Mule to sell it elsewhere (and ultimately do that with a whole bunch of different ressources).

So in my warehouse I set up the buying price at the lowest (becouse without buying offer Station Mule doesn't work) and the selling price at the higher price (as ,again, without selling offer Travel Mule doesn't work) .

In this configuration, my Station Mules work just fine, but as I indicated, the Travel Mules just buy and sell to the same Warehouse over and over.

![Screenshot_22](https://user-images.githubusercontent.com/71597536/93714105-c47a4100-fb60-11ea-9402-98f728054497.png)

I then tried to remove the buy offer from my station, which resolved the issue with the Travel Mule, but then it's the Station Mules that stopped working.

I tried to fiddle with all the options in the mule, to switch to different kinds of mules or the fiddle with the prices in my warehouse but I wasn't able to make it work until now.

To me the problem is with the "Target All NPC Station" option which seems to include our source station. If I'm right, a way to fix that would be to just exclude it from the targets in the option, or to include a list of banned station (instead of a list of handpicked station where you want to sell, which is ridiculous when I need to pick every NPC station but mine).

Did I misunderstood something here or is this a real issue ?

Sorry for the bother if it's a known issue / misuse of the mod.

**Comment by bhayden53** [comment]
Unfortunately with the buy and sell prices inverted (i.e. buy lower than sell), this is pretty much the behavior that's expected. I mean, that's what the AI might be doing as well. They can make money off of you without even leaving the station.

Eventually, if we ever get back to writing more code, the travel mule shouldn't trade at the same station like this. But the inverted buy/sell prices is your problem.

I pretty much never manually set prices. I just let the manager do it, he'll respond to stock levels with appropriate price adjustments.

**Comment by BinaryJourney** [comment]
Thanks for the answer, ~~however the price doesn't seem to be the problem here.~~

~~I already tried to change it before (and double checked after your answer just to be sure), but whatever the buy / sell price on my station (max sell / min buy, the other way around, same price or even automatic pricing) the problem persist.~~

But I also just realized that I was using Mule Overhaul, which is a slighly modified version of your mod (in which the issue has already been reported).

I'm really sorry for the confusion, i'm ashamed.

Thanks a lot for your time, and for the wonderfull work you all pulled on the mod.

**Comment by bhayden53** [comment]
No worries, hopefully one day we'll get back to work and fix the lingering issues. Most of them are small, but I know myself personally, I got a bit fed up with X4 and am only really watching for major bugs. There is one at the moment regarding multiple trades in a single run, but it's subtle to notice.
