### ISSUE TITLE
[QUESTION]: Problems with StationSupplyMule

### ISSUE THREAD

**Issue by Reisser696** [Misunderstood-Wookiee/Mules-and-Warehosues-Extended#94]
Hello. I have the following problem: I would like to use a StationSupplyMule (6.1.2 from Nexus) to connect a station (only ores and gases) to a factory complex. There are 6 systems in between (too far for Vanilla-Trader)

So I took a freighter, 5-star pilot in, StationSupplyMule started, Source: Mining Camp, Target: Factory Complex> Start

The target has a need (partly zero inventory) and enough money.

Unfortunately nothing happens. The freighter is looking for trade orders, that's it.

The stations were initially configured to only buy / sell to my faction. I then made it easier and easier, piece by piece - but nothing is happening here either.

Then the freighter is assigned directly to the mining camp (there is always enough money). Here too: nothing happens. Then the destination (factory complex) marked as a warehouse - nothing. Also all other options that looks to make it easier for the freighter to do it's job. 

Are there any problems with X4 3.30 or how do I get the mod to work as I need it? The simple SupplyMule works (at least from what I have seen) without any problems with the AI ​​and my stations.

**Comment by bhayden53** [comment]
The target has low inventory, but does it have buy orders?

Can you post pictures of:
1) the logical overview screens of both stations
2) the mule order screen when he's searching for trades, with the options visible

**Comment by Reisser696** [comment]
Ah - forget it - sorry! I just realised that in X4 freighters can't carry ores and fuels - only containers. So the mule don't have a chance to find a trade job. My fault! But thanks for your quick reaction :)  

We can close this question

**Comment by bhayden53** [comment]
FWIW, miners can be used as mules, so you may still be able to get one to work by using the appropriate miner.

**Comment by Misunderstood-Wookiee** [comment]
I'm still here btw I'm read stuff.
Just don't play same as you.
